package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/KDreynolds/COBOLabunga/parser"
)

type stringConst struct {
	name string
	data []byte
}

type Codegen struct {
	prog          *parser.Program
	buf           strings.Builder
	indent        int
	strConsts     []stringConst
	targetTriple  string
	isWasm        bool
	isBareMetal   bool
}

func New(prog *parser.Program) *Codegen {
	return &Codegen{prog: prog, targetTriple: "x86_64-pc-linux-gnu"}
}

func (c *Codegen) SetTarget(triple string) {
	c.targetTriple = triple
	c.isWasm = strings.Contains(triple, "wasm")
	c.isBareMetal = strings.Contains(triple, "none-elf") || strings.Contains(triple, "bare")
}

func (c *Codegen) isBare() bool {
	return c.isBareMetal
}

func (c *Codegen) Generate() string {
	c.buf.Reset()
	c.strConsts = nil

	c.emit("; Generated by COBOLabunga v0.1")
	c.emit("target triple = \"" + c.targetTriple + "\"")
	c.emit("")

	if !c.isBare() {
		c.emit("declare i32 @puts(ptr)")
		c.emit("declare i32 @printf(ptr, ...)")
		c.emit("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)")
		c.emit("declare ptr @fgets(ptr, i32, ptr)")
		c.emit("declare i32 @atoi(ptr)")
		c.emit("@stdin = external global ptr")
		c.emit("")
		c.emit("declare i32 @cob_http_get(ptr, ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_http_post(ptr, ptr, ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_http_put(ptr, ptr, ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_http_patch(ptr, ptr, ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_http_delete(ptr, ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_json_str(ptr, i64, ptr, ptr, i64)")
		c.emit("declare i32 @cob_json_int(ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_http_listen(i32, ptr)")
		c.emit("declare i32 @cob_http_respond(i32, ptr, ptr)")
		c.emit("declare i32 @cob_http_respond_set_header(ptr, ptr, i64)")
		c.emit("declare i32 @cob_http_request_field(ptr, ptr, i64)")
		c.emit("declare i32 @cob_picx_eq(ptr, i64, ptr)")
		c.emit("declare void @cob_string_init(ptr, i64, ptr)")
		c.emit("declare void @cob_string_add_size(ptr, i64)")
		c.emit("declare void @cob_string_add_until_space(ptr, i64)")
		c.emit("declare void @cob_string_add_until_delim(ptr, i64, ptr, i64)")
		c.emit("declare void @cob_string_finish(ptr, ptr)")
		c.emit("declare void @cob_unstring_init(ptr, i64, ptr, ptr)")
		c.emit("declare i32 @cob_unstring_extract(ptr, i64, ptr, i64, ptr, ptr, i64, ptr, i64)")
		c.emit("declare void @cob_unstring_finish(ptr, ptr, ptr)")
		c.emit("")
	} else {
		c.emit("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)")
		c.emit("")
	}

	c.emitWorkingStorage()
	c.emitMain()

	if c.prog.ProcedureDivision != nil {
		for _, para := range c.prog.ProcedureDivision.Paragraphs {
			c.emitParagraph(para)
		}
	}

	c.emitStringConsts()

	if c.isBare() {
		c.emitBareHelpers()
	}

	return c.buf.String()
}

func (c *Codegen) emit(format string, args ...interface{}) {
	for i := 0; i < c.indent; i++ {
		c.buf.WriteString("  ")
	}
	c.buf.WriteString(fmt.Sprintf(format, args...))
	c.buf.WriteString("\n")
}

func (c *Codegen) emitWorkingStorage() {
	if c.prog.WorkingStorage == nil {
		return
	}
	for _, item := range c.prog.WorkingStorage.Items {
		c.emitDataItem(item)
	}
	if len(c.prog.WorkingStorage.Items) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitDataItem(item *parser.DataItem) {
	if item.Picture != nil {
		name := sanitize(item.Name)
		switch item.Picture.Type {
		case parser.PicX:
			size := item.Picture.Size
			init := c.picXInitializer(item.Value, size)
			c.emit("@%s = global [%d x i8] %s", name, size+1, init)
		case parser.Pic9:
			init := c.pic9Initializer(item.Value)
			c.emit("@%s = global i32 %s", name, init)
		}
	}
	for _, child := range item.Children {
		c.emitDataItem(child)
	}
}

func (c *Codegen) picXInitializer(value string, size int) string {
	buf := make([]byte, size)
	copy(buf, value)
	for i := len(value); i < size; i++ {
		buf[i] = ' '
	}
	return c.llvmArrayInit(buf)
}

func (c *Codegen) pic9Initializer(value string) string {
	if value == "" {
		return "0"
	}
	return value
}

func (c *Codegen) llvmArrayInit(data []byte) string {
	var sb strings.Builder
	sb.WriteString("[")
	for i, b := range data {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("i8 %d", uint8(b)))
	}
	sb.WriteString(", i8 0]")
	return sb.String()
}

func (c *Codegen) addStringConst(data []byte) string {
	name := fmt.Sprintf(".str.%d", len(c.strConsts))
	c.strConsts = append(c.strConsts, stringConst{name: name, data: data})
	return name
}

func (c *Codegen) emitStringConsts() {
	for _, sc := range c.strConsts {
		init := c.llvmArrayInit(sc.data)
		c.emit("@%s = private unnamed_addr constant [%d x i8] %s",
			sc.name, len(sc.data)+1, init)
	}
	if len(c.strConsts) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitMain() {
	isWasm := strings.Contains(c.targetTriple, "wasm")
	entryName := "main"
	if isWasm {
		entryName = "__main_argc_argv"
	}
	if c.isBare() {
		c.emit("define void @_start() noreturn {")
	} else {
		c.emit("define hidden i32 @%s(i32 %%argc, ptr %%argv) nounwind {", entryName)
	}
	c.indent++
	firstPara := c.firstParagraphName()
	if firstPara != "" {
		c.emit("call void @%s()", firstPara)
	}
	if c.isBare() {
		c.emit("ret void")
	} else {
		c.emit("ret i32 0")
	}
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitParagraph(para *parser.Paragraph) {
	name := sanitize(para.Name)
	c.emit("define void @%s() {", name)
	c.indent++
	c.emit("entry:")
	c.indent++
	c.emitStatements(para.Statements)
	c.emit("ret void")
	c.indent--
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitStatements(stmts []parser.Statement) {
	for _, stmt := range stmts {
		c.emitStatement(stmt)
	}
}

func (c *Codegen) emitStatement(stmt parser.Statement) {
	switch s := stmt.(type) {
	case *parser.Display:
		c.emitDisplay(s)
	case *parser.StopRun:
		c.emit("ret void")
	case *parser.Move:
		c.emitMove(s)
	case *parser.Compute:
		c.emitCompute(s)
	case *parser.Perform:
		c.emitPerform(s)
	case *parser.If:
		c.emitIf(s)
	case *parser.Evaluate:
		c.emitEvaluate(s)
	case *parser.HttpGet:
		c.emitHttpGet(s)
	case *parser.HttpPost:
		c.emitHttpPost(s)
	case *parser.HttpPut:
		c.emitHttpPut(s)
	case *parser.HttpPatch:
		c.emitHttpPatch(s)
	case *parser.HttpDelete:
		c.emitHttpDelete(s)
	case *parser.HttpListen:
		c.emitHttpListen(s)
	case *parser.HttpRespond:
		c.emitHttpRespond(s)
	case *parser.StringStmt:
		c.emitString(s)
	case *parser.Accept:
		c.emitAccept(s)
	case *parser.Initialize:
		c.emitInitialize(s)
	case *parser.UnstringStmt:
		c.emitUnstring(s)
	case *parser.Peek:
		c.emitPeek(s)
	case *parser.Poke:
		c.emitPoke(s)
	case *parser.PortIn:
		c.emitPortIn(s)
	case *parser.PortOut:
		c.emitPortOut(s)
	}
}

func (c *Codegen) emitAccept(s *parser.Accept) {
	if c.isBare() {
		panic("ACCEPT not yet supported on bare metal target")
	}
	name := sanitize(s.Name)
	size := c.fieldSize(s.Name)

	if c.isNumericField(s.Name) {
		// Read string, convert to int
		tmp := c.nextRegister()
		c.emit("%%%s = alloca i8, i64 32", tmp)
		in := c.nextRegister()
		c.emit("%%%s = load ptr, ptr @stdin", in)
		c.emit("call ptr @fgets(ptr %%%s, i32 31, ptr %%%s)", tmp, in)
		val := c.nextRegister()
		c.emit("%%%s = call i32 @atoi(ptr %%%s)", val, tmp)
		c.emit("store i32 %%%s, ptr @%s", val, name)
	} else {
		// Read string directly into field
		ptr := c.nextRegister()
		sz := int64(size) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0", ptr, sz, name)
		in := c.nextRegister()
		c.emit("%%%s = load ptr, ptr @stdin", in)
		c.emit("call ptr @fgets(ptr %%%s, i32 %d, ptr %%%s)", ptr, sz, in)

		// Strip newline: scan and replace \n with space
		nlLoop := c.nextLabel("accept.nl")
		nlBody := c.nextLabel("accept.nlbody")
		nlRep := c.nextLabel("accept.nlrep")
		nlNext := c.nextLabel("accept.nlnext")
		nlDone := c.nextLabel("accept.nldone")
		idxReg := c.nextRegister()
		c.emit("%%%s = alloca i32", idxReg)
		c.emit("store i32 0, ptr %%%s", idxReg)
		c.emit("br label %%%s", nlLoop)
		c.emit("%s:", nlLoop)
		idx := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", idx, idxReg)
		chk := c.nextRegister()
		c.emit("%%%s = icmp slt i32 %%%s, %d", chk, idx, size)
		c.emit("br i1 %%%s, label %%%s, label %%%s", chk, nlBody, nlDone)
		c.emit("%s:", nlBody)
		cp := c.nextRegister()
		c.emit("%%%s = getelementptr i8, ptr %%%s, i32 %%%s", cp, ptr, idx)
		bv := c.nextRegister()
		c.emit("%%%s = load i8, ptr %%%s", bv, cp)
		isnl := c.nextRegister()
		c.emit("%%%s = icmp eq i8 %%%s, 10", isnl, bv)
		c.emit("br i1 %%%s, label %%%s, label %%%s", isnl, nlRep, nlNext)
		c.emit("%s:", nlRep)
		c.emit("store i8 32, ptr %%%s", cp)
		c.emit("br label %%%s", nlDone)
		c.emit("%s:", nlNext)
		nxt := c.nextRegister()
		c.emit("%%%s = add i32 %%%s, 1", nxt, idx)
		c.emit("store i32 %%%s, ptr %%%s", nxt, idxReg)
		c.emit("br label %%%s", nlLoop)
		c.emit("%s:", nlDone)
	}
}

func (c *Codegen) emitPeek(s *parser.Peek) {
	if !c.isBare() {
		panic("PEEK requires --target x86-bare")
	}
	addr := c.emitExpr(s.Address)
	addr64 := c.nextRegister()
	c.emit("%%%s = sext i32 %s to i64", addr64, addr)
	ptr := c.nextRegister()
	into := sanitize(s.Into)
	c.emit("%%%s = inttoptr i64 %%%s to ptr", ptr, addr64)
	val := c.nextRegister()
	c.emit("%%%s = load i8, ptr %%%s", val, ptr)
	ext := c.nextRegister()
	c.emit("%%%s = zext i8 %%%s to i32", ext, val)
	c.emit("store i32 %%%s, ptr @%s", ext, into)
}

func (c *Codegen) emitPoke(s *parser.Poke) {
	if !c.isBare() {
		panic("POKE requires --target x86-bare")
	}
	addr := c.emitExpr(s.Address)
	addr64 := c.nextRegister()
	c.emit("%%%s = sext i32 %s to i64", addr64, addr)
	val := c.emitExpr(s.Value)
	ptr := c.nextRegister()
	trunc := c.nextRegister()
	c.emit("%%%s = inttoptr i64 %%%s to ptr", ptr, addr64)
	c.emit("%%%s = trunc i32 %s to i8", trunc, val)
	c.emit("store i8 %%%s, ptr %%%s", trunc, ptr)
}

func (c *Codegen) emitPortIn(s *parser.PortIn) {
	if !c.isBare() {
		panic("PORT-IN requires --target x86-bare")
	}
	port := c.emitExpr(s.Port)
	port16 := c.nextRegister()
	c.emit("%%%s = trunc i32 %s to i16", port16, port)
	reg := c.nextRegister()
	into := sanitize(s.Into)
	c.emit("%%%s = call i8 asm \"inb $1, $0\", \"={al},{dx}\"(i16 %%%s)", reg, port16)
	ext := c.nextRegister()
	c.emit("%%%s = zext i8 %%%s to i32", ext, reg)
	c.emit("store i32 %%%s, ptr @%s", ext, into)
}

func (c *Codegen) emitPortOut(s *parser.PortOut) {
	if !c.isBare() {
		panic("PORT-OUT requires --target x86-bare")
	}
	port := c.emitExpr(s.Port)
	port16 := c.nextRegister()
	c.emit("%%%s = trunc i32 %s to i16", port16, port)
	val := c.emitExpr(s.Value)
	trunc := c.nextRegister()
	c.emit("%%%s = trunc i32 %s to i8", trunc, val)
	c.emit("call void asm \"outb $0, $1\", \"{al},{dx}\"(i8 %%%s, i16 %%%s)", trunc, port16)
}

func (c *Codegen) emitInitialize(s *parser.Initialize) {
	for _, name := range s.Items {
		size := c.fieldSize(name)
		if c.isNumericField(name) {
			c.emit("store i32 0, ptr @%s", sanitize(name))
		} else {
			buf := bytes.Repeat([]byte{32}, size) // spaces
			cn := c.addStringConst(buf)
			sz := int64(size)
			c.emit("call void @llvm.memcpy.p0.p0.i64("+
				"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
				"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
				"i64 %d, i1 false)",
				sz+1, sanitize(name), sz+1, cn, sz)
		}
	}
}

func (c *Codegen) emitDisplay(s *parser.Display) {
	if c.isBare() {
		c.emitBareDisplay(s)
		return
	}
	for _, item := range s.Items {
		switch expr := item.(type) {
		case *parser.IdentifierExpr:
			if c.isNumericField(expr.Name) {
				reg := c.nextRegister()
				cn := c.addStringConst([]byte("%d"))
				c.emit("%%%s = load i32, ptr @%s", reg, sanitize(expr.Name))
				c.emit("call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @%s, i64 0, i64 0), i32 %%%s)",
					cn, reg)
			} else {
				name := sanitize(expr.Name)
				reg := c.nextRegister()
				c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
					reg, c.fieldSize(expr.Name)+1, name)
				c.emit("call i32 @puts(ptr %%%s)", reg)
			}
		case *parser.StringLiteralExpr:
			cn := c.addStringConst([]byte(expr.Value))
			sz := len(expr.Value) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		case *parser.IntegerLiteralExpr:
			str := fmt.Sprintf("%d", expr.Value)
			cn := c.addStringConst([]byte(str))
			sz := len(str) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		}
	}
}

func (c *Codegen) emitBareDisplay(s *parser.Display) {
	for _, item := range s.Items {
		switch expr := item.(type) {
		case *parser.IdentifierExpr:
			if c.isNumericField(expr.Name) {
				reg := c.nextRegister()
				c.emit("%%%s = load i32, ptr @%s", reg, sanitize(expr.Name))
				c.emit("call void @cob_bare_print_int(i32 %%%s)", reg)
			} else {
				name := sanitize(expr.Name)
				reg := c.nextRegister()
				size := c.fieldSize(expr.Name)
				c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
					reg, size+1, name)
				c.emit("call void @cob_bare_print_str(ptr %%%s, i64 %d)", reg, size)
			}
		case *parser.StringLiteralExpr:
			cn := c.addStringConst([]byte(expr.Value))
			sz := len(expr.Value)
			c.emit("call void @cob_bare_print_str(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), i64 %d)",
				sz+1, cn, sz)
		case *parser.IntegerLiteralExpr:
			str := fmt.Sprintf("%d", expr.Value)
			cn := c.addStringConst([]byte(str))
			sz := len(str)
			c.emit("call void @cob_bare_print_str(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), i64 %d)",
				sz+1, cn, sz)
		}
	}
}

func (c *Codegen) emitString(s *parser.StringStmt) {
	if c.isWasm {
		c.emitStringWasm(s)
		return
	}

	dest := sanitize(s.Into)
	destSize := int64(c.fieldSize(s.Into))

	// Set up pointer
	var ptrAlloca string
	pointerArg := "ptr null"
	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrReg := c.nextRegister()
		ptrAlloca = ptrReg + ".ptr"
		c.emit("%%%s = load i32, ptr @%s", ptrReg, ptrName)
		c.emit("%%%s = alloca i32", ptrAlloca)
		c.emit("store i32 %%%s, ptr %%%s", ptrReg, ptrAlloca)
		pointerArg = "ptr %" + ptrAlloca
	}

	c.emit("call void @cob_string_init(ptr @%s, i64 %d, %s)",
		dest, destSize, pointerArg)

	for _, f := range s.Sending {
		srcReg := c.emitExprPtr(f.Source)
		srcSize := c.exprValueSize(f.Source)

		switch f.Delimiter.Type {
		case parser.DelimBySize:
			c.emit("call void @cob_string_add_size(ptr %s, i64 %d)", srcReg, srcSize)
		case parser.DelimBySpace:
			c.emit("call void @cob_string_add_until_space(ptr %s, i64 %d)", srcReg, srcSize)
		case parser.DelimByIdentifier:
			delimReg := c.emitExprPtr(f.Delimiter.Value)
			delimSize := c.exprValueSize(f.Delimiter.Value)
			c.emit("call void @cob_string_add_until_delim(ptr %s, i64 %d, ptr %s, i64 %d)",
				srcReg, srcSize, delimReg, delimSize)
		}
	}

	overflowReg := c.nextRegister()
	overflowAlloca := overflowReg + ".ovf"
	c.emit("%%%s = alloca i32", overflowAlloca)
	c.emit("store i32 0, ptr %%%s", overflowAlloca)
	c.emit("call void @cob_string_finish(%s, ptr %%%s)", pointerArg, overflowAlloca)

	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ptrVal, ptrAlloca)
		c.emit("store i32 %%%s, ptr @%s", ptrVal, ptrName)
	}

	c.emitStringOverflow(s, overflowAlloca)
}

func (c *Codegen) emitStringOverflow(s *parser.StringStmt, overflowAlloca string) {
	if len(s.OnOverflow) > 0 || len(s.NotOnOverflow) > 0 {
		labelOverflow := c.nextLabel("string.overflow")
		labelNoOverflow := c.nextLabel("string.nooverflow")
		labelEnd := c.nextLabel("string.end")

		ovVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ovVal, overflowAlloca)
		c.emit("%%ovf = icmp ne i32 %%%s, 0", ovVal)
		c.emit("br i1 %%ovf, label %%%s, label %%%s", labelOverflow, labelNoOverflow)

		c.emit("%s:", labelOverflow)
		c.indent++
		c.emitStatements(s.OnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNoOverflow)
		c.indent++
		c.emitStatements(s.NotOnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelEnd)
	}
}

func (c *Codegen) emitStringWasm(s *parser.StringStmt) {
	dest := sanitize(s.Into)
	dest64 := int64(c.fieldSize(s.Into))
	destSize := int32(dest64)

	// alloca for position (1-indexed)
	posReg := c.nextRegister()
	c.emit("%%%s = alloca i32", posReg)
	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		pv := c.nextRegister()
		c.emit("%%%s = load i32, ptr @%s", pv, ptrName)
		c.emit("store i32 %%%s, ptr %%%s", pv, posReg)
	} else {
		c.emit("store i32 1, ptr %%%s", posReg)
	}

	// alloca for overflow
	ovfReg := c.nextRegister()
	c.emit("%%%s = alloca i32", ovfReg)
	c.emit("store i32 0, ptr %%%s", ovfReg)

	// dest base pointer
	destBase := c.nextRegister()
	sz := dest64 + 1
	c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0", destBase, sz, dest)

	for _, f := range s.Sending {
		srcReg := c.emitExprPtr(f.Source)
		srcSize := int32(c.exprValueSize(f.Source))

		curPos := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", curPos, posReg)

		pos0 := c.nextRegister()
		c.emit("%%%s = sub i32 %%%s, 1", pos0, curPos)

		destPtr := c.nextRegister()
		c.emit("%%%s = getelementptr i8, ptr %%%s, i32 %%%s", destPtr, destBase, pos0)

		switch f.Delimiter.Type {
		case parser.DelimBySize:
			c.emit("call void @llvm.memcpy.p0.p0.i64(ptr %%%s, ptr %s, i64 %d, i1 false)",
				destPtr, srcReg, int64(srcSize))
			newPos := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, %d", newPos, curPos, srcSize)
			c.emit("store i32 %%%s, ptr %%%s", newPos, posReg)

		case parser.DelimBySpace:
			// Copy source, scan for space byte-by-byte
			scanLoop := c.nextLabel("str.scan")
			scanBody := c.nextLabel("str.scanbody")
			scanCopy := c.nextLabel("str.scancopy")
			scanDone := c.nextLabel("str.scandone")
			siReg := c.nextRegister()
			c.emit("%%%s = alloca i32", siReg)
			c.emit("store i32 0, ptr %%%s", siReg)
			diReg := c.nextRegister()
			c.emit("%%%s = alloca i32", diReg)
			c.emit("store i32 0, ptr %%%s", diReg)

			c.emit("br label %%%s", scanLoop)
			c.emit("%s:", scanLoop)

			si := c.nextRegister()
			c.emit("%%%s = load i32, ptr %%%s", si, siReg)
			di := c.nextRegister()
			c.emit("%%%s = load i32, ptr %%%s", di, diReg)

			// Check bounds
			sok := c.nextRegister()
			c.emit("%%%s = icmp slt i32 %%%s, %d", sok, si, srcSize)
			dok := c.nextRegister()
			c.emit("%%%s = icmp slt i32 %%%s, %d", dok, di, destSize)
			cont := c.nextRegister()
			c.emit("%%%s = and i1 %%%s, %%%s", cont, sok, dok)
			c.emit("br i1 %%%s, label %%%s, label %%%s", cont, scanBody, scanDone)

			c.emit("%s:", scanBody)
			// Load source byte
			srcPtr := c.nextRegister()
			c.emit("%%%s = getelementptr i8, ptr %s, i64 %%%s", srcPtr, srcReg, si)
			bv := c.nextRegister()
			c.emit("%%%s = load i8, ptr %%%s", bv, srcPtr)

			// Check for space
			isSp := c.nextRegister()
			c.emit("%%%s = icmp eq i8 %%%s, 32", isSp, bv)
			c.emit("br i1 %%%s, label %%%s, label %%%s", isSp, scanDone, scanCopy)

			c.emit("%s:", scanCopy)
			// Store to dest
			dp := c.nextRegister()
			c.emit("%%%s = getelementptr i8, ptr %%%s, i64 %%%s", dp, destPtr, di)
			c.emit("store i8 %%%s, ptr %%%s", bv, dp)

			// Advance source and dest indices
			nsi := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, 1", nsi, si)
			c.emit("store i32 %%%s, ptr %%%s", nsi, siReg)
			ndi := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, 1", ndi, di)
			c.emit("store i32 %%%s, ptr %%%s", ndi, diReg)
			c.emit("br label %%%s", scanLoop)
			c.emit("%s:", scanDone)

			// Update position: advance past the bytes we copied + the space delimiter
			sfinal := c.nextRegister()
			c.emit("%%%s = load i32, ptr %%%s", sfinal, siReg)
			ns := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, 2", ns, sfinal) // +1 for space itself
			c.emit("store i32 %%%s, ptr %%%s", ns, posReg)

		case parser.DelimByIdentifier:
			// Full copy for now
			c.emit("call void @llvm.memcpy.p0.p0.i64(ptr %%%s, ptr %s, i64 %d, i1 false)",
				destPtr, srcReg, int64(srcSize))
			newPos3 := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, %d", newPos3, curPos, srcSize)
			c.emit("store i32 %%%s, ptr %%%s", newPos3, posReg)
		}
	}

	// Space-pad remaining
	c.emitStringSpacePad(destBase, destSize, posReg)

	// Check overflow
	fp := c.nextRegister()
	c.emit("%%%s = load i32, ptr %%%s", fp, posReg)
	chk := c.nextRegister()
	c.emit("%%%s = icmp sgt i32 %%%s, %d", chk, fp, destSize)
	ovf := c.nextRegister()
	c.emit("%%%s = zext i1 %%%s to i32", ovf, chk)
	c.emit("store i32 %%%s, ptr %%%s", ovf, ovfReg)

	if s.Pointer != "" {
		pn := sanitize(s.Pointer)
		pv := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", pv, posReg)
		c.emit("store i32 %%%s, ptr @%s", pv, pn)
	}

	c.emitStringOverflow(s, ovfReg)
}

func (c *Codegen) emitStringSpacePad(destBase string, destSize int32, posAlloca string) {
	padDone := c.nextLabel("str.padend")
	padLoop := c.nextLabel("str.padloop")
	padIdx := c.nextRegister()
	c.emit("%%%s = alloca i32", padIdx)
	// padIdx = pos (1-indexed), convert to 0-indexed
	pi := c.nextRegister()
	c.emit("%%%s = load i32, ptr %%%s", pi, posAlloca)
	pi0 := c.nextRegister()
	c.emit("%%%s = sub i32 %%%s, 1", pi0, pi)
	c.emit("store i32 %%%s, ptr %%%s", pi0, padIdx)

	c.emit("br label %%%s", padLoop)
	c.emit("%s:", padLoop)
	ci := c.nextRegister()
	c.emit("%%%s = load i32, ptr %%%s", ci, padIdx)
	cc := c.nextRegister()
	c.emit("%%%s = icmp slt i32 %%%s, %d", cc, ci, destSize)
	c.emit("br i1 %%%s, label %%%s, label %%%s", cc, padDone, padDone)

	// space fill byte
	pp := c.nextRegister()
	c.emit("%%%s = getelementptr i8, ptr %%%s, i32 %%%s", pp, destBase, ci)
	c.emit("store i8 32, ptr %%%s", pp)
	ni := c.nextRegister()
	c.emit("%%%s = add i32 %%%s, 1", ni, ci)
	c.emit("store i32 %%%s, ptr %%%s", ni, padIdx)
	c.emit("br label %%%s", padLoop)
	c.emit("%s:", padDone)
}

func (c *Codegen) emitUnstring(s *parser.UnstringStmt) {
	if c.isWasm {
		c.emitUnstringWasm(s)
		return
	}

	srcReg := c.emitExprPtr(s.Source)
	srcSize := c.exprValueSize(s.Source)

	var ptrAlloca string
	pointerArg := "ptr null"
	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrReg := c.nextRegister()
		ptrAlloca = ptrReg + ".ptr"
		c.emit("%%%s = load i32, ptr @%s", ptrReg, ptrName)
		c.emit("%%%s = alloca i32", ptrAlloca)
		c.emit("store i32 %%%s, ptr %%%s", ptrReg, ptrAlloca)
		pointerArg = "ptr %" + ptrAlloca
	}

	var talAlloca string
	tallyArg := "ptr null"
	if s.Tallying != "" {
		talReg := c.nextRegister()
		talAlloca = talReg + ".tal"
		c.emit("%%%s = alloca i32", talAlloca)
		c.emit("store i32 0, ptr %%%s", talAlloca)
		tallyArg = "ptr %" + talAlloca
	}

	c.emit("call void @cob_unstring_init(ptr %s, i64 %d, %s, %s)",
		srcReg, srcSize, pointerArg, tallyArg)

	for _, f := range s.Into {
		destName := sanitize(f.Destination)
		destSize := int64(c.fieldSize(f.Destination))

		delimInArg := "ptr null"
		delimInSize := int64(0)
		if f.DelimiterIn != "" {
			delimInSize = int64(c.fieldSize(f.DelimiterIn))
			delimInArg = "ptr @" + sanitize(f.DelimiterIn)
		}
		countInArg := "ptr null"
		if f.CountIn != "" {
			cntReg := c.nextRegister()
			cAlloca := cntReg + ".cnt"
			c.emit("%%%s = alloca i32", cAlloca)
			countInArg = "ptr %" + cAlloca
		}

		delim1Expr := "ptr null"
		delim1Size := int64(0)
		delim2Expr := "ptr null"
		delim2Size := int64(0)
		if len(s.Delimiters) > 0 {
			switch s.Delimiters[0].Type {
			case parser.DelimByIdentifier:
				r := c.emitExprPtr(s.Delimiters[0].Value)
				delim1Expr = "ptr %" + r
				delim1Size = c.exprValueSize(s.Delimiters[0].Value)
			case parser.DelimBySpace:
				cn := c.addStringConst([]byte(" "))
				delim1Expr = "ptr getelementptr inbounds ([2 x i8], ptr @" + cn + ", i64 0, i64 0)"
				delim1Size = 1
			}
			if len(s.Delimiters) > 1 {
				switch s.Delimiters[1].Type {
				case parser.DelimByIdentifier:
					r := c.emitExprPtr(s.Delimiters[1].Value)
					delim2Expr = "ptr %" + r
					delim2Size = c.exprValueSize(s.Delimiters[1].Value)
				case parser.DelimBySpace:
					cn := c.addStringConst([]byte(" "))
					delim2Expr = "ptr getelementptr inbounds ([2 x i8], ptr @" + cn + ", i64 0, i64 0)"
					delim2Size = 1
				}
			}
		}

		c.emit("call i32 @cob_unstring_extract(ptr @%s, i64 %d, %s, i64 %d, %s, %s, i64 %d, %s, i64 %d)",
			destName, destSize,
			delimInArg, delimInSize, countInArg,
			delim1Expr, delim1Size,
			delim2Expr, delim2Size)
	}

	overflowReg := c.nextRegister()
	overflowAlloca := overflowReg + ".ovf"
	c.emit("%%%s = alloca i32", overflowAlloca)
	c.emit("store i32 0, ptr %%%s", overflowAlloca)
	c.emit("call void @cob_unstring_finish(%s, %s, ptr %%%s)",
		pointerArg, tallyArg, overflowAlloca)

	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ptrVal, ptrAlloca)
		c.emit("store i32 %%%s, ptr @%s", ptrVal, ptrName)
	}

	if s.Tallying != "" {
		talName := sanitize(s.Tallying)
		talVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", talVal, talAlloca)
		c.emit("store i32 %%%s, ptr @%s", talVal, talName)
	}

	c.emitUnstringOverflow(s, overflowAlloca)
}

func (c *Codegen) emitUnstringOverflow(s *parser.UnstringStmt, overflowAlloca string) {
	if len(s.OnOverflow) > 0 || len(s.NotOnOverflow) > 0 {
		labelOverflow := c.nextLabel("unstring.overflow")
		labelNoOverflow := c.nextLabel("unstring.nooverflow")
		labelEnd := c.nextLabel("unstring.end")

		ovVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ovVal, overflowAlloca)
		c.emit("%%ovf = icmp ne i32 %%%s, 0", ovVal)
		c.emit("br i1 %%ovf, label %%%s, label %%%s", labelOverflow, labelNoOverflow)

		c.emit("%s:", labelOverflow)
		c.indent++
		c.emitStatements(s.OnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNoOverflow)
		c.indent++
		c.emitStatements(s.NotOnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelEnd)
	}
}

func (c *Codegen) emitUnstringWasm(s *parser.UnstringStmt) {
	srcReg := c.emitExprPtr(s.Source)
	srcSize32 := int32(c.exprValueSize(s.Source))

	// alloca for source position (0-indexed)
	posReg := c.nextRegister()
	c.emit("%%%s = alloca i32", posReg)
	if s.Pointer != "" {
		pn := sanitize(s.Pointer)
		pv := c.nextRegister()
		c.emit("%%%s = load i32, ptr @%s", pv, pn)
		// Convert 1-indexed to 0-indexed
		p0 := c.nextRegister()
		c.emit("%%%s = sub i32 %%%s, 1", p0, pv)
		c.emit("store i32 %%%s, ptr %%%s", p0, posReg)
	} else {
		c.emit("store i32 0, ptr %%%s", posReg)
	}

	// alloca for overflow, tally
	ovfReg := c.nextRegister()
	c.emit("%%%s = alloca i32", ovfReg)
	c.emit("store i32 0, ptr %%%s", ovfReg)

	var talReg string
	if s.Tallying != "" {
		talReg = c.nextRegister()
		c.emit("%%%s = alloca i32", talReg)
		c.emit("store i32 0, ptr %%%s", talReg)
	}

	for idx, f := range s.Into {
		if idx > 0 {
			// Advance past delimiter
			cp := c.nextRegister()
			c.emit("%%%s = load i32, ptr %%%s", cp, posReg)
			np := c.nextRegister()
			c.emit("%%%s = add i32 %%%s, 1", np, cp)
			c.emit("store i32 %%%s, ptr %%%s", np, posReg)
		}

		destName := sanitize(f.Destination)
		destSize32 := int32(c.fieldSize(f.Destination))

		// Scan from current position for space or end
		destBase := c.nextRegister()
		dsz := int64(c.fieldSize(f.Destination)) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0", destBase, dsz, destName)

		scanLoop := c.nextLabel("unstr.scan")
		scanBody := c.nextLabel("unstr.scanbody")
		scanCopy := c.nextLabel("unstr.scancopy")
		scanDone := c.nextLabel("unstr.scandone")

		// Copy bytes from src+pos to dest until space or src end
		cpReg := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", cpReg, posReg)

		// dest write index
		diReg := c.nextRegister()
		c.emit("%%%s = alloca i32", diReg)
		c.emit("store i32 0, ptr %%%s", diReg)

		c.emit("br label %%%s", scanLoop)
		c.emit("%s:", scanLoop)

		cp2 := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", cp2, posReg)
		di2 := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", di2, diReg)

		// Check if source position is within bounds
		inBounds := c.nextRegister()
		c.emit("%%%s = icmp slt i32 %%%s, %d", inBounds, cp2, srcSize32)
		// Check if dest is within bounds
		destOk := c.nextRegister()
		c.emit("%%%s = icmp slt i32 %%%s, %d", destOk, di2, destSize32)
		cont := c.nextRegister()
		c.emit("%%%s = and i1 %%%s, %%%s", cont, inBounds, destOk)
		c.emit("br i1 %%%s, label %%%s, label %%%s", cont, scanBody, scanDone)

		c.emit("%s:", scanBody)
		// Load source byte
		srcBytePtr := c.nextRegister()
		c.emit("%%%s = getelementptr i8, ptr %s, i32 %%%s", srcBytePtr, srcReg, cp2)
		sb := c.nextRegister()
		c.emit("%%%s = load i8, ptr %%%s", sb, srcBytePtr)

		// Check if space
		isSpace := c.nextRegister()
		c.emit("%%%s = icmp eq i8 %%%s, 32", isSpace, sb)
		c.emit("br i1 %%%s, label %%%s, label %%%s", isSpace, scanDone, scanCopy)

		c.emit("%s:", scanCopy)
		// Store byte to dest
		destPtr := c.nextRegister()
		c.emit("%%%s = getelementptr i8, ptr %%%s, i32 %%%s", destPtr, destBase, di2)
		c.emit("store i8 %%%s, ptr %%%s", sb, destPtr)

		// Advance positions
		np2 := c.nextRegister()
		c.emit("%%%s = add i32 %%%s, 1", np2, cp2)
		c.emit("store i32 %%%s, ptr %%%s", np2, posReg)
		nd := c.nextRegister()
		c.emit("%%%s = add i32 %%%s, 1", nd, di2)
		c.emit("store i32 %%%s, ptr %%%s", nd, diReg)
		c.emit("br label %%%s", scanLoop)
		c.emit("%s:", scanDone)

		// Store count if COUNT IN
		if f.CountIn != "" {
			cntName := sanitize(f.CountIn)
			di3 := c.nextRegister()
			c.emit("%%%s = load i32, ptr %%%s", di3, diReg)
			c.emit("store i32 %%%s, ptr @%s", di3, cntName)
		}

		// Space-fill remaining dest
		padLoop := c.nextLabel("unstr.padloop")
		padBody := c.nextLabel("unstr.padbody")
		padDone := c.nextLabel("unstr.padend")
		c.emit("br label %%%s", padLoop)
		c.emit("%s:", padLoop)
		di4 := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", di4, diReg)
		padOk := c.nextRegister()
		c.emit("%%%s = icmp slt i32 %%%s, %d", padOk, di4, destSize32)
		c.emit("br i1 %%%s, label %%%s, label %%%s", padOk, padBody, padDone)
		c.emit("%s:", padBody)
		pp := c.nextRegister()
		c.emit("%%%s = getelementptr i8, ptr %%%s, i32 %%%s", pp, destBase, di4)
		c.emit("store i8 32, ptr %%%s", pp)
		nd2 := c.nextRegister()
		c.emit("%%%s = add i32 %%%s, 1", nd2, di4)
		c.emit("store i32 %%%s, ptr %%%s", nd2, diReg)
		c.emit("br label %%%s", padLoop)
		c.emit("%s:", padDone)
	}

	// Store back pointer (convert 0-indexed to 1-indexed)
	if s.Pointer != "" {
		pn := sanitize(s.Pointer)
		cp := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", cp, posReg)
		cp1 := c.nextRegister()
		c.emit("%%%s = add i32 %%%s, 1", cp1, cp)
		c.emit("store i32 %%%s, ptr @%s", cp1, pn)
	}

	if s.Tallying != "" {
		tn := sanitize(s.Tallying)
		tv := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", tv, talReg)
		c.emit("store i32 %%%s, ptr @%s", tv, tn)
	}

	c.emitUnstringOverflow(s, ovfReg)
}

func (c *Codegen) emitMove(s *parser.Move) {
	name := sanitize(s.To)
	switch from := s.From.(type) {
	case *parser.StringLiteralExpr:
		size := c.fieldSize(s.To)
		buf := make([]byte, size)
		copy(buf, from.Value)
		for i := len(from.Value); i < size; i++ {
			buf[i] = ' '
		}
		cn := c.addStringConst(buf)
		c.emit("call void @llvm.memcpy.p0.p0.i64("+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"i64 %d, i1 false)",
			size+1, name, size+1, cn, size+1)
	case *parser.IntegerLiteralExpr:
		c.emit("store i32 %d, ptr @%s", from.Value, name)
	case *parser.IdentifierExpr:
		fromName := sanitize(from.Name)
		c.emit("%%tmp = load i32, ptr @%s", fromName)
		c.emit("store i32 %%tmp, ptr @%s", name)
	}
}

func (c *Codegen) emitCompute(s *parser.Compute) {
	name := sanitize(s.Target)
	result := c.emitExpr(s.Expr)
	c.emit("store i32 %s, ptr @%s", result, name)
}

func (c *Codegen) emitExpr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IntegerLiteralExpr:
		tmp := c.nextRegister()
		c.emit("%%%s = add i32 %d, 0", tmp, e.Value)
		return "%" + tmp
	case *parser.IdentifierExpr:
		tmp := c.nextRegister()
		name := sanitize(e.Name)
		c.emit("%%%s = load i32, ptr @%s", tmp, name)
		return "%" + tmp
	case *parser.BinaryExpr:
		tmp := c.nextRegister()

		switch e.Operator {
		case parser.OpAdd, parser.OpSub, parser.OpMul, parser.OpDiv,
			parser.OpGt, parser.OpLt, parser.OpGe, parser.OpLe:
			left := c.emitExpr(e.Left)
			right := c.emitExpr(e.Right)
			switch e.Operator {
			case parser.OpAdd:
				c.emit("%%%s = add i32 %s, %s", tmp, left, right)
			case parser.OpSub:
				c.emit("%%%s = sub i32 %s, %s", tmp, left, right)
			case parser.OpMul:
				c.emit("%%%s = mul i32 %s, %s", tmp, left, right)
			case parser.OpDiv:
				c.emit("%%%s = sdiv i32 %s, %s", tmp, left, right)
			case parser.OpGt:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sgt i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpLt:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp slt i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpGe:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sge i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpLe:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sle i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			}
			return "%" + tmp

		case parser.OpEq:
			// String comparison: use cob_picx_eq if either operand is a string
			leftIsString := c.isStringExpr(e.Left)
			rightIsString := c.isStringExpr(e.Right)

			if leftIsString || rightIsString {
				leftPtr := c.emitExprPtr(e.Left)
				rightPtr := c.emitExprPtr(e.Right)
				leftSize := c.exprSize(e.Left)
				c.emit("%%%s = call i32 @cob_picx_eq(ptr %s, i64 %d, ptr %s)",
					tmp, leftPtr, leftSize, rightPtr)
				return "%" + tmp
			}
			// Numeric comparison
			left := c.emitExpr(e.Left)
			right := c.emitExpr(e.Right)
			cmptmp := c.nextRegister()
			c.emit("%%%s = icmp eq i32 %s, %s", cmptmp, left, right)
			c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			return "%" + tmp
		}
		return "%" + tmp
	}
	return "0"
}

func (c *Codegen) emitPerform(s *parser.Perform) {
	if s.Varying != nil {
		c.emitPerformVarying(s)
		return
	}
	if s.Until != nil {
		c.emitPerformUntil(s)
		return
	}
	name := sanitize(s.Paragraph)
	c.emit("call void @%s()", name)
}

func (c *Codegen) emitPerformUntil(s *parser.Perform) {
	labelCond := c.nextLabel("perf.cond")
	labelBody := c.nextLabel("perf.body")
	labelEnd := c.nextLabel("perf.end")

	c.emit("br label %%%s", labelCond)

	// Condition check
	c.emit("%s:", labelCond)
	c.indent++
	condVal := c.emitExpr(s.Until)
	c.emit("%%perf_done = icmp ne i32 %s, 0", condVal)
	c.emit("br i1 %%perf_done, label %%%s, label %%%s", labelEnd, labelBody)
	c.indent--

	// Loop body
	c.emit("%s:", labelBody)
	c.indent++
	c.emitStatements(s.Body)
	c.emit("br label %%%s", labelCond)
	c.indent--

	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitPerformVarying(s *parser.Perform) {
	vp := s.Varying
	varName := sanitize(vp.Variable)

	// Initialize: var = from
	fromVal := c.emitExpr(vp.From)
	c.emit("store i32 %s, ptr @%s", fromVal, varName)

	labelCond := c.nextLabel("perf.cond")
	labelBody := c.nextLabel("perf.body")
	labelEnd := c.nextLabel("perf.end")

	c.emit("br label %%%s", labelCond)

	// Condition check
	c.emit("%s:", labelCond)
	c.indent++
	condVal := c.emitExpr(vp.Until)
	c.emit("%%perf_done = icmp ne i32 %s, 0", condVal)
	c.emit("br i1 %%perf_done, label %%%s, label %%%s", labelEnd, labelBody)
	c.indent--

	// Loop body
	c.emit("%s:", labelBody)
	c.indent++
	c.emitStatements(s.Body)
	// Increment: var = var + by
	varReg := c.nextRegister()
	byVal := c.emitExpr(vp.By)
	c.emit("%%%s = load i32, ptr @%s", varReg, varName)
	nextReg := c.nextRegister()
	c.emit("%%%s = add i32 %%%s, %s", nextReg, varReg, byVal)
	c.emit("store i32 %%%s, ptr @%s", nextReg, varName)
	c.emit("br label %%%s", labelCond)
	c.indent--

	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitIf(s *parser.If) {
	cond := c.emitExpr(s.Condition)
	cmpReg := c.nextRegister()
	labelThen := c.nextLabel("if.then")
	labelElse := c.nextLabel("if.else")
	labelMerge := c.nextLabel("if.end")

	c.emit("%%%s = icmp ne i32 %s, 0", cmpReg, cond)
	c.emit("br i1 %%%s, label %%%s, label %%%s", cmpReg, labelThen, labelElse)

	c.emit("%s:", labelThen)
	c.indent++
	c.emitStatements(s.ThenBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelElse)
	c.indent++
	c.emitStatements(s.ElseBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelMerge)
}

func (c *Codegen) emitEvaluate(s *parser.Evaluate) {
	labelEnd := c.nextLabel("eval.end")

	isStringEval := c.isStringExpr(s.Subject)

	for i, wc := range s.WhenClauses {
		labelNext := c.nextLabel("eval.next")
		labelBody := c.nextLabel("eval.body")

		if isStringEval {
			// String comparison via cob_picx_eq
			leftPtr := c.emitExprPtr(s.Subject)
			rightPtr := c.emitExprPtr(wc.Values[0])
			leftSize := c.exprSize(s.Subject)
			tmp := c.nextRegister()
			c.emit("%%%s = call i32 @cob_picx_eq(ptr %s, i64 %d, ptr %s)",
				tmp, leftPtr, leftSize, rightPtr)
			c.emit("%%cmp%d = icmp ne i32 %%%s, 0", i, tmp)
		} else {
			// Numeric comparison
			subject := c.emitExpr(s.Subject)
			whenVal := c.emitExpr(wc.Values[0])
			c.emit("%%cmp%d = icmp eq i32 %s, %s", i, subject, whenVal)
		}
		c.emit("br i1 %%cmp%d, label %%%s, label %%%s", i, labelBody, labelNext)

		c.emit("%s:", labelBody)
		c.indent++
		c.emitStatements(wc.Body)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNext)
	}

	if len(s.WhenOther) > 0 {
		c.emitStatements(s.WhenOther)
	}

	c.emit("br label %%%s", labelEnd)
	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitExprPtr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		name := sanitize(e.Name)
		reg := c.nextRegister()
		sz := c.fieldSize(e.Name) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		return "%" + reg
	case *parser.StringLiteralExpr:
		cn := c.addStringConst([]byte(e.Value))
		sz := len(e.Value) + 1
		return fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", sz, cn)
	case *parser.IntegerLiteralExpr:
		s := fmt.Sprintf("%d", e.Value)
		cn := c.addStringConst([]byte(s))
		sz := len(s) + 1
		return fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", sz, cn)
	}
	return "null"
}

func (c *Codegen) emitHttpGet(s *parser.HttpGet) {
	c.emitHttpCall("cob_http_get", s.URL, nil, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpPost(s *parser.HttpPost) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_post", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPut(s *parser.HttpPut) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_put", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPatch(s *parser.HttpPatch) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_patch", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpDelete(s *parser.HttpDelete) {
	c.emitHttpCall("cob_http_delete", s.URL, nil, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpCall(funcName string, urlExpr parser.Expression, sendingExpr parser.Expression,
	giving, mapping *string, status string, onException, notOnException []parser.Statement, hasBody bool) {

	urlPtr := c.emitExprPtr(urlExpr)

	bodyPtr := "null"
	if hasBody && sendingExpr != nil {
		bodyPtr = c.emitExprPtr(sendingExpr)
	}

	// Response buffer: either the GIVING field or a temp alloca for MAPPING
	respPtr := "null"
	respSize := int64(0)
	lenReg := c.nextRegister()
	c.emit("%%%s = alloca i64, i64 1", lenReg)
	c.emit("store i64 0, ptr %%%s", lenReg)

	if giving != nil {
		name := sanitize(*giving)
		reg := c.nextRegister()
		sz := c.fieldSize(*giving) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		respPtr = "%" + reg
		respSize = int64(sz)
	} else if mapping != nil {
		// Allocate temp buffer for JSON response, 4096 bytes
		bufReg := c.nextRegister()
		c.emit("%%%s = alloca [4096 x i8], i64 1", bufReg)
		respReg := c.nextRegister()
		c.emit("%%%s = getelementptr [4096 x i8], ptr %%%s, i64 0, i64 0",
			respReg, bufReg)
		respPtr = "%" + respReg
		respSize = 4096
	}

	statusPtr := "null"
	if status != "" {
		statusPtr = "@" + sanitize(status)
	}

	resultReg := c.nextRegister()
	if hasBody {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, bodyPtr, respPtr, respSize, lenReg, statusPtr)
	} else {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, respPtr, respSize, lenReg, statusPtr)
	}

	// If MAPPING, emit per-field JSON extraction
	if mapping != nil {
		c.emitJsonMapping(*mapping, respPtr, lenReg)
	}

	hasOn := len(onException) > 0
	hasNotOn := len(notOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(onException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(notOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

func (c *Codegen) emitJsonMapping(groupName, respPtr, lenReg string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	lenV := c.nextRegister()
	c.emit("%%%s = load i64, ptr %%%s", lenV, lenReg)

	for _, child := range children {
		if child.Picture == nil {
			continue
		}
		fn := c.addStringConst([]byte(child.Name))
		fnSz := len(child.Name) + 1
		fnGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", fnSz, fn)

		switch child.Picture.Type {
		case parser.PicX:
			fieldReg := c.nextRegister()
			sz := child.Picture.Size + 1
			c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
				fieldReg, sz, sanitize(child.Name))
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_json_str(ptr %s, i64 %%%s, ptr %s, ptr %%%s, i64 %d)",
				discard, respPtr, lenV, fnGep, fieldReg, int64(child.Picture.Size))
		case parser.Pic9:
			fieldPtr := "@" + sanitize(child.Name)
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_json_int(ptr %s, i64 %%%s, ptr %s, ptr %s)",
				discard, respPtr, lenV, fnGep, fieldPtr)
		}
	}
}

func (c *Codegen) emitHttpListen(s *parser.HttpListen) {
	resultReg := c.nextRegister()
	statusPtr := "null"
	if s.Status != "" {
		statusPtr = "@" + sanitize(s.Status)
	}
	c.emit("%%%s = call i32 @cob_http_listen(i32 %d, ptr %s)",
		resultReg, s.Port, statusPtr)

	if s.Mapping != nil {
		c.emitHttpListenMapping(*s.Mapping)
	}
	if s.Headers != nil && s.Headers.Group != "" {
		c.emitHttpListenMapping(s.Headers.Group)
	}

	hasOn := len(s.OnException) > 0
	hasNotOn := len(s.NotOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(s.OnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(s.NotOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

func (c *Codegen) emitHttpListenMapping(groupName string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	for _, child := range children {
		if child.Picture == nil {
			continue
		}
		fn := c.addStringConst([]byte(child.Name))
		fnSz := len(child.Name) + 1
		fnGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", fnSz, fn)

		switch child.Picture.Type {
		case parser.PicX:
			fieldReg := c.nextRegister()
			sz := child.Picture.Size + 1
			c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
				fieldReg, sz, sanitize(child.Name))
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_http_request_field(ptr %s, ptr %%%s, i64 %d)",
				discard, fnGep, fieldReg, int64(child.Picture.Size))
		}
	}
}

func (c *Codegen) emitHttpRespondHeaders(groupName string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	for _, child := range children {
		if child.Picture == nil || child.Picture.Type != parser.PicX {
			continue
		}
		hdrName := c.addStringConst([]byte(child.Name))
		hdrNameSz := len(child.Name) + 1
		hdrNameGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", hdrNameSz, hdrName)

		fieldReg := c.nextRegister()
		sz := child.Picture.Size + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			fieldReg, sz, sanitize(child.Name))
		discard := c.nextRegister()
		c.emit("%%%s = call i32 @cob_http_respond_set_header(ptr %s, ptr %%%s, i64 %d)",
			discard, hdrNameGep, fieldReg, int64(child.Picture.Size))
	}
}

func (c *Codegen) emitHttpRespond(s *parser.HttpRespond) {
	if s.Headers != nil && s.Headers.Group != "" {
		c.emitHttpRespondHeaders(s.Headers.Group)
	}

	bodyPtr := "null"
	if s.Body != nil {
		bodyPtr = c.emitExprPtr(s.Body)
	}
	contentTypePtr := "null"
	if s.ContentType != nil {
		contentTypePtr = c.emitExprPtr(s.ContentType)
	}

	resultReg := c.nextRegister()
	c.emit("%%%s = call i32 @cob_http_respond(i32 %d, ptr %s, ptr %s)",
		resultReg, s.Status, bodyPtr, contentTypePtr)

	hasOn := len(s.OnException) > 0
	hasNotOn := len(s.NotOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(s.OnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(s.NotOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

var registerCounter int
var labelCounter int

func (c *Codegen) nextRegister() string {
	registerCounter++
	return fmt.Sprintf("r%d", registerCounter)
}

func (c *Codegen) nextLabel(prefix string) string {
	labelCounter++
	return fmt.Sprintf("%s.%d", prefix, labelCounter)
}

func sanitize(name string) string {
	s := strings.ReplaceAll(name, "-", "_")
	s = strings.ReplaceAll(s, "<", "_")
	s = strings.ReplaceAll(s, ">", "_")
	return "cob." + s
}

func (c *Codegen) firstParagraphName() string {
	if c.prog.ProcedureDivision != nil && len(c.prog.ProcedureDivision.Paragraphs) > 0 {
		return sanitize(c.prog.ProcedureDivision.Paragraphs[0].Name)
	}
	return ""
}

func (c *Codegen) fieldSize(name string) int {
	if c.prog.WorkingStorage == nil {
		return 0
	}
	return findFieldSize(name, c.prog.WorkingStorage.Items)
}

func (c *Codegen) exprSize(expr parser.Expression) int64 {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return int64(c.fieldSize(e.Name))
	case *parser.StringLiteralExpr:
		return int64(len(e.Value))
	case *parser.IntegerLiteralExpr:
		return 4
	}
	return 1
}

func (c *Codegen) exprName(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return e.Name
	case *parser.StringLiteralExpr:
		return ""
	case *parser.IntegerLiteralExpr:
		return ""
	}
	return ""
}

func (c *Codegen) exprValueSize(expr parser.Expression) int64 {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return int64(c.fieldSize(e.Name))
	case *parser.StringLiteralExpr:
		return int64(len(e.Value))
	case *parser.IntegerLiteralExpr:
		return 4 // max int32 digits (no null terminator needed)
	}
	return 1
}

func (c *Codegen) isNumericField(name string) bool {
	if c.prog.WorkingStorage == nil {
		return false
	}
	return findFieldType(name, c.prog.WorkingStorage.Items)
}

func findFieldType(name string, items []*parser.DataItem) bool {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Type == parser.Pic9
		}
		if len(item.Children) > 0 {
			if num := findFieldType(name, item.Children); num {
				return true
			}
		}
	}
	return false
}

func (c *Codegen) isStringExpr(expr parser.Expression) bool {
	switch e := expr.(type) {
	case *parser.StringLiteralExpr:
		return true
	case *parser.IdentifierExpr:
		return !c.isNumericField(e.Name)
	default:
		return false
	}
}

func findFieldSize(name string, items []*parser.DataItem) int {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Size
		}
		if len(item.Children) > 0 {
			if size := findFieldSize(name, item.Children); size > 0 {
				return size
			}
		}
	}
	return 0
}

func (c *Codegen) findGroupChildren(name string) []*parser.DataItem {
	if c.prog.WorkingStorage == nil {
		return nil
	}
	return findGroupItemChildren(name, c.prog.WorkingStorage.Items)
}

func findGroupItemChildren(name string, items []*parser.DataItem) []*parser.DataItem {
	for _, item := range items {
		if item.Name == name {
			return item.Children
		}
		if len(item.Children) > 0 {
			if found := findGroupItemChildren(name, item.Children); found != nil {
				return found
			}
		}
	}
	return nil
}

func (c *Codegen) emitBareHelpers() {
	c.emit("")
	c.emit("; VGA cursor position (col 0-based)")
	c.emit("@cob.vga.col = global i32 0")
	c.emit("")
	c.buf.WriteString(vgaCode)
	c.buf.WriteString("\n")
}

var vgaCode = `
define void @cob_bare_print_str(ptr %str, i64 %len) {
entry:
  %vga = inttoptr i64 7047296 to ptr
  %col = load i32, ptr @cob.vga.col
  %col_sext = sext i32 %col to i64
  %vga_start = getelementptr i8, ptr %vga, i64 %col_sext
  br label %loop
loop:
  %i = phi i64 [ 0, %entry ], [ %next_i, %body ]
  %dst = phi ptr [ %vga_start, %entry ], [ %dst_next, %body ]
  %done = icmp eq i64 %i, %len
  br i1 %done, label %done_bb, label %body
body:
  %ch_ptr = getelementptr i8, ptr %str, i64 %i
  %ch = load i8, ptr %ch_ptr
  store i8 %ch, ptr %dst
  %attr = getelementptr i8, ptr %dst, i64 1
  store i8 7, ptr %attr
  %next_i = add i64 %i, 1
  %dst_next = getelementptr i8, ptr %dst, i64 2
  br label %loop
done_bb:
  %new_col = add i64 %col_sext, %len
  %new_col_trunc = trunc i64 %new_col to i32
  store i32 %new_col_trunc, ptr @cob.vga.col
  ret void
}

define void @cob_bare_print_int(i32 %val) {
entry:
  %vga = inttoptr i64 7047296 to ptr
  %col = load i32, ptr @cob.vga.col
  %col_sext = sext i32 %col to i64
  %vga_start = getelementptr i8, ptr %vga, i64 %col_sext
  %zero = icmp eq i32 %val, 0
  br i1 %zero, label %zero_bb, label %nz_entry
zero_bb:
  store i8 48, ptr %vga_start
  %za = getelementptr i8, ptr %vga_start, i64 1
  store i8 7, ptr %za
  store i32 2, ptr @cob.vga.col
  ret void
nz_entry:
  %neg = icmp slt i32 %val, 0
  br i1 %neg, label %neg_bb, label %digits
neg_bb:
  store i8 45, ptr %vga_start
  %na = getelementptr i8, ptr %vga_start, i64 1
  store i8 7, ptr %na
  %neg_val = sub i32 0, %val
  br label %digits
digits:
  %n = phi i32 [ %val, %nz_entry ], [ %neg_val, %neg_bb ]
  %base = phi ptr [ %vga_start, %nz_entry ], [ %vga_start, %neg_bb ]
  %neg_flag = phi i32 [ 0, %nz_entry ], [ 1, %neg_bb ]
  %chars = call i32 @cob_utoa(i32 %n, ptr %base)
  %total = add i32 %neg_flag, %chars
  %col_old = load i32, ptr @cob.vga.col
  %col_new = add i32 %col_old, %total
  store i32 %col_new, ptr @cob.vga.col
  ret void
}

define internal i32 @cob_utoa(i32 %n, ptr %buf) {
entry:
  %tmp = alloca [12 x i8], align 1
  %is_zero = icmp eq i32 %n, 0
  br i1 %is_zero, label %zero_bb, label %conv
zero_bb:
  store i8 48, ptr %buf
  %za = getelementptr i8, ptr %buf, i64 1
  store i8 7, ptr %za
  ret i32 1
conv:
  br label %conv_loop
conv_loop:
  %val = phi i32 [ %n, %conv ], [ %div, %conv_loop ]
  %pos = phi i64 [ 0, %conv ], [ %p_next, %conv_loop ]
  %div = udiv i32 %val, 10
  %rem = urem i32 %val, 10
  %dig = trunc i32 %rem to i8
  %dig_ch = add i8 48, %dig
  %slot = getelementptr i8, ptr %tmp, i64 %pos
  store i8 %dig_ch, ptr %slot
  %p_next = add i64 %pos, 1
  %div_end = icmp eq i32 %div, 0
  br i1 %div_end, label %conv_done, label %conv_loop
conv_done:
  %len = trunc i64 %p_next to i32
  br label %copy_loop
copy_loop:
  %ci = phi i64 [ 0, %conv_done ], [ %ci_next, %copy_loop ]
  %ri = phi i64 [ %p_next, %conv_done ], [ %ri_next, %copy_loop ]
  %ri_dec = sub i64 %ri, 1
  %src = getelementptr i8, ptr %tmp, i64 %ri_dec
  %ch = load i8, ptr %src
  %dst_p = getelementptr i8, ptr %buf, i64 %ci
  store i8 %ch, ptr %dst_p
  %attrd = getelementptr i8, ptr %dst_p, i64 1
  store i8 7, ptr %attrd
  %ci_next = add i64 %ci, 1
  %ri_next = sub i64 %ri_dec, 0
  %copy_end = icmp eq i64 %ri_dec, 0
  br i1 %copy_end, label %final, label %copy_loop
final:
  ret i32 %len
}
`
