package codegen

import (
	"fmt"
	"strings"

	"github.com/KDreynolds/COBOLabunga/parser"
)

type stringConst struct {
	name string
	data []byte
}

type Codegen struct {
	prog          *parser.Program
	buf           strings.Builder
	indent        int
	strConsts     []stringConst
	targetTriple  string
}

func New(prog *parser.Program) *Codegen {
	return &Codegen{prog: prog, targetTriple: "x86_64-pc-linux-gnu"}
}

func (c *Codegen) SetTarget(triple string) {
	c.targetTriple = triple
}

func (c *Codegen) Generate() string {
	c.buf.Reset()
	c.strConsts = nil

	c.emit("; Generated by COBOLabunga v0.1")
	c.emit("target triple = \"" + c.targetTriple + "\"")
	c.emit("")

	c.emit("declare i32 @puts(ptr)")
	c.emit("declare i32 @printf(ptr, ...)")
	c.emit("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)")
	c.emit("")
	c.emit("declare i32 @cob_http_get(ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_post(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_put(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_patch(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_delete(ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_json_str(ptr, i64, ptr, ptr, i64)")
	c.emit("declare i32 @cob_json_int(ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_listen(i32, ptr)")
	c.emit("declare i32 @cob_http_respond(i32, ptr, ptr)")
	c.emit("declare i32 @cob_http_respond_set_header(ptr, ptr, i64)")
	c.emit("declare i32 @cob_http_request_field(ptr, ptr, i64)")
	c.emit("declare i32 @cob_picx_eq(ptr, i64, ptr)")
	c.emit("declare void @cob_string_init(ptr, i64, ptr)")
	c.emit("declare void @cob_string_add_size(ptr, i64)")
	c.emit("declare void @cob_string_add_until_space(ptr, i64)")
	c.emit("declare void @cob_string_add_until_delim(ptr, i64, ptr, i64)")
	c.emit("declare void @cob_string_finish(ptr, ptr)")
	c.emit("declare void @cob_unstring_init(ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_unstring_extract(ptr, i64, ptr, i64, ptr, ptr, i64, ptr, i64)")
	c.emit("declare void @cob_unstring_finish(ptr, ptr, ptr)")
	c.emit("")

	c.emitWorkingStorage()
	c.emitMain()

	if c.prog.ProcedureDivision != nil {
		for _, para := range c.prog.ProcedureDivision.Paragraphs {
			c.emitParagraph(para)
		}
	}

	c.emitStringConsts()
	return c.buf.String()
}

func (c *Codegen) emit(format string, args ...interface{}) {
	for i := 0; i < c.indent; i++ {
		c.buf.WriteString("  ")
	}
	c.buf.WriteString(fmt.Sprintf(format, args...))
	c.buf.WriteString("\n")
}

func (c *Codegen) emitWorkingStorage() {
	if c.prog.WorkingStorage == nil {
		return
	}
	for _, item := range c.prog.WorkingStorage.Items {
		c.emitDataItem(item)
	}
	if len(c.prog.WorkingStorage.Items) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitDataItem(item *parser.DataItem) {
	if item.Picture != nil {
		name := sanitize(item.Name)
		switch item.Picture.Type {
		case parser.PicX:
			size := item.Picture.Size
			init := c.picXInitializer(item.Value, size)
			c.emit("@%s = global [%d x i8] %s", name, size+1, init)
		case parser.Pic9:
			init := c.pic9Initializer(item.Value)
			c.emit("@%s = global i32 %s", name, init)
		}
	}
	for _, child := range item.Children {
		c.emitDataItem(child)
	}
}

func (c *Codegen) picXInitializer(value string, size int) string {
	buf := make([]byte, size)
	copy(buf, value)
	for i := len(value); i < size; i++ {
		buf[i] = ' '
	}
	return c.llvmArrayInit(buf)
}

func (c *Codegen) pic9Initializer(value string) string {
	if value == "" {
		return "0"
	}
	return value
}

func (c *Codegen) llvmArrayInit(data []byte) string {
	var sb strings.Builder
	sb.WriteString("[")
	for i, b := range data {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("i8 %d", uint8(b)))
	}
	sb.WriteString(", i8 0]")
	return sb.String()
}

func (c *Codegen) addStringConst(data []byte) string {
	name := fmt.Sprintf(".str.%d", len(c.strConsts))
	c.strConsts = append(c.strConsts, stringConst{name: name, data: data})
	return name
}

func (c *Codegen) emitStringConsts() {
	for _, sc := range c.strConsts {
		init := c.llvmArrayInit(sc.data)
		c.emit("@%s = private unnamed_addr constant [%d x i8] %s",
			sc.name, len(sc.data)+1, init)
	}
	if len(c.strConsts) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitMain() {
	isWasm := strings.Contains(c.targetTriple, "wasm")
	entryName := "main"
	if isWasm {
		entryName = "__main_argc_argv"
	}
	c.emit("define hidden i32 @%s(i32 %%argc, ptr %%argv) nounwind {", entryName)
	c.indent++
	firstPara := c.firstParagraphName()
	if firstPara != "" {
		c.emit("call void @%s()", firstPara)
	}
	c.emit("ret i32 0")
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitParagraph(para *parser.Paragraph) {
	name := sanitize(para.Name)
	c.emit("define void @%s() {", name)
	c.indent++
	c.emit("entry:")
	c.indent++
	c.emitStatements(para.Statements)
	c.indent--
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitStatements(stmts []parser.Statement) {
	for _, stmt := range stmts {
		c.emitStatement(stmt)
	}
}

func (c *Codegen) emitStatement(stmt parser.Statement) {
	switch s := stmt.(type) {
	case *parser.Display:
		c.emitDisplay(s)
	case *parser.StopRun:
		c.emit("ret void")
	case *parser.Move:
		c.emitMove(s)
	case *parser.Compute:
		c.emitCompute(s)
	case *parser.Perform:
		c.emitPerform(s)
	case *parser.If:
		c.emitIf(s)
	case *parser.Evaluate:
		c.emitEvaluate(s)
	case *parser.HttpGet:
		c.emitHttpGet(s)
	case *parser.HttpPost:
		c.emitHttpPost(s)
	case *parser.HttpPut:
		c.emitHttpPut(s)
	case *parser.HttpPatch:
		c.emitHttpPatch(s)
	case *parser.HttpDelete:
		c.emitHttpDelete(s)
	case *parser.HttpListen:
		c.emitHttpListen(s)
	case *parser.HttpRespond:
		c.emitHttpRespond(s)
	case *parser.StringStmt:
		c.emitString(s)
	case *parser.UnstringStmt:
		c.emitUnstring(s)
	}
}

func (c *Codegen) emitDisplay(s *parser.Display) {
	for _, item := range s.Items {
		switch expr := item.(type) {
		case *parser.IdentifierExpr:
			if c.isNumericField(expr.Name) {
				reg := c.nextRegister()
				cn := c.addStringConst([]byte("%d"))
				c.emit("%%%s = load i32, ptr @%s", reg, sanitize(expr.Name))
				c.emit("call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @%s, i64 0, i64 0), i32 %%%s)",
					cn, reg)
			} else {
				name := sanitize(expr.Name)
				reg := c.nextRegister()
				c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
					reg, c.fieldSize(expr.Name)+1, name)
				c.emit("call i32 @puts(ptr %%%s)", reg)
			}
		case *parser.StringLiteralExpr:
			cn := c.addStringConst([]byte(expr.Value))
			sz := len(expr.Value) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		case *parser.IntegerLiteralExpr:
			str := fmt.Sprintf("%d", expr.Value)
			cn := c.addStringConst([]byte(str))
			sz := len(str) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		}
	}
}

func (c *Codegen) emitString(s *parser.StringStmt) {
	dest := sanitize(s.Into)
	destSize := int64(c.fieldSize(s.Into))

	// Set up pointer
	var ptrAlloca string
	pointerArg := "ptr null"
	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrReg := c.nextRegister()
		ptrAlloca = ptrReg + ".ptr"
		c.emit("%%%s = load i32, ptr @%s", ptrReg, ptrName)
		c.emit("%%%s = alloca i32", ptrAlloca)
		c.emit("store i32 %%%s, ptr %%%s", ptrReg, ptrAlloca)
		pointerArg = "ptr %" + ptrAlloca
	}

	c.emit("call void @cob_string_init(ptr @%s, i64 %d, %s)",
		dest, destSize, pointerArg)

	for _, f := range s.Sending {
		srcReg := c.emitExprPtr(f.Source)
		srcSize := c.exprValueSize(f.Source)

		switch f.Delimiter.Type {
		case parser.DelimBySize:
			c.emit("call void @cob_string_add_size(ptr %s, i64 %d)", srcReg, srcSize)
		case parser.DelimBySpace:
			c.emit("call void @cob_string_add_until_space(ptr %s, i64 %d)", srcReg, srcSize)
		case parser.DelimByIdentifier:
			delimReg := c.emitExprPtr(f.Delimiter.Value)
			delimSize := c.exprValueSize(f.Delimiter.Value)
			c.emit("call void @cob_string_add_until_delim(ptr %s, i64 %d, ptr %s, i64 %d)",
				srcReg, srcSize, delimReg, delimSize)
		}
	}

	overflowReg := c.nextRegister()
	overflowAlloca := overflowReg + ".ovf"
	c.emit("%%%s = alloca i32", overflowAlloca)
	c.emit("store i32 0, ptr %%%s", overflowAlloca)
	c.emit("call void @cob_string_finish(%s, ptr %%%s)", pointerArg, overflowAlloca)

	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ptrVal, ptrAlloca)
		c.emit("store i32 %%%s, ptr @%s", ptrVal, ptrName)
	}

	if len(s.OnOverflow) > 0 || len(s.NotOnOverflow) > 0 {
		labelOverflow := c.nextLabel("string.overflow")
		labelNoOverflow := c.nextLabel("string.nooverflow")
		labelEnd := c.nextLabel("string.end")

		ovVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ovVal, overflowAlloca)
		c.emit("%%ovf = icmp ne i32 %%%s, 0", ovVal)
		c.emit("br i1 %%ovf, label %%%s, label %%%s", labelOverflow, labelNoOverflow)

		c.emit("%s:", labelOverflow)
		c.indent++
		c.emitStatements(s.OnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNoOverflow)
		c.indent++
		c.emitStatements(s.NotOnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelEnd)
	}
}

func (c *Codegen) emitUnstring(s *parser.UnstringStmt) {
	srcReg := c.emitExprPtr(s.Source)
	srcSize := c.exprValueSize(s.Source)

	var ptrAlloca string
	pointerArg := "ptr null"
	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrReg := c.nextRegister()
		ptrAlloca = ptrReg + ".ptr"
		c.emit("%%%s = load i32, ptr @%s", ptrReg, ptrName)
		c.emit("%%%s = alloca i32", ptrAlloca)
		c.emit("store i32 %%%s, ptr %%%s", ptrReg, ptrAlloca)
		pointerArg = "ptr %" + ptrAlloca
	}

	var talAlloca string
	tallyArg := "ptr null"
	if s.Tallying != "" {
		talReg := c.nextRegister()
		talAlloca = talReg + ".tal"
		c.emit("%%%s = alloca i32", talAlloca)
		c.emit("store i32 0, ptr %%%s", talAlloca)
		tallyArg = "ptr %" + talAlloca
	}

	c.emit("call void @cob_unstring_init(ptr %s, i64 %d, %s, %s)",
		srcReg, srcSize, pointerArg, tallyArg)

	for _, f := range s.Into {
		destName := sanitize(f.Destination)
		destSize := int64(c.fieldSize(f.Destination))

		delimInArg := "ptr null"
		delimInSize := int64(0)
		if f.DelimiterIn != "" {
			delimInSize = int64(c.fieldSize(f.DelimiterIn))
			delimInArg = "ptr @" + sanitize(f.DelimiterIn)
		}
		countInArg := "ptr null"
		if f.CountIn != "" {
			cntReg := c.nextRegister()
			cAlloca := cntReg + ".cnt"
			c.emit("%%%s = alloca i32", cAlloca)
			countInArg = "ptr %" + cAlloca
		}

		delim1Expr := "ptr null"
		delim1Size := int64(0)
		delim2Expr := "ptr null"
		delim2Size := int64(0)
		if len(s.Delimiters) > 0 {
			switch s.Delimiters[0].Type {
			case parser.DelimByIdentifier:
				r := c.emitExprPtr(s.Delimiters[0].Value)
				delim1Expr = "ptr %" + r
				delim1Size = c.exprValueSize(s.Delimiters[0].Value)
			case parser.DelimBySpace:
				cn := c.addStringConst([]byte(" "))
				delim1Expr = "ptr getelementptr inbounds ([2 x i8], ptr @" + cn + ", i64 0, i64 0)"
				delim1Size = 1
			}
			if len(s.Delimiters) > 1 {
				switch s.Delimiters[1].Type {
				case parser.DelimByIdentifier:
					r := c.emitExprPtr(s.Delimiters[1].Value)
					delim2Expr = "ptr %" + r
					delim2Size = c.exprValueSize(s.Delimiters[1].Value)
				case parser.DelimBySpace:
					cn := c.addStringConst([]byte(" "))
					delim2Expr = "ptr getelementptr inbounds ([2 x i8], ptr @" + cn + ", i64 0, i64 0)"
					delim2Size = 1
				}
			}
		}

		c.emit("call i32 @cob_unstring_extract(ptr @%s, i64 %d, %s, i64 %d, %s, %s, i64 %d, %s, i64 %d)",
			destName, destSize,
			delimInArg, delimInSize, countInArg,
			delim1Expr, delim1Size,
			delim2Expr, delim2Size)
	}

	overflowReg := c.nextRegister()
	overflowAlloca := overflowReg + ".ovf"
	c.emit("%%%s = alloca i32", overflowAlloca)
	c.emit("store i32 0, ptr %%%s", overflowAlloca)
	c.emit("call void @cob_unstring_finish(%s, %s, ptr %%%s)",
		pointerArg, tallyArg, overflowAlloca)

	if s.Pointer != "" {
		ptrName := sanitize(s.Pointer)
		ptrVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ptrVal, ptrAlloca)
		c.emit("store i32 %%%s, ptr @%s", ptrVal, ptrName)
	}

	if s.Tallying != "" {
		talName := sanitize(s.Tallying)
		talVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", talVal, talAlloca)
		c.emit("store i32 %%%s, ptr @%s", talVal, talName)
	}

	if len(s.OnOverflow) > 0 || len(s.NotOnOverflow) > 0 {
		labelOverflow := c.nextLabel("unstring.overflow")
		labelNoOverflow := c.nextLabel("unstring.nooverflow")
		labelEnd := c.nextLabel("unstring.end")

		ovVal := c.nextRegister()
		c.emit("%%%s = load i32, ptr %%%s", ovVal, overflowAlloca)
		c.emit("%%ovf = icmp ne i32 %%%s, 0", ovVal)
		c.emit("br i1 %%ovf, label %%%s, label %%%s", labelOverflow, labelNoOverflow)

		c.emit("%s:", labelOverflow)
		c.indent++
		c.emitStatements(s.OnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNoOverflow)
		c.indent++
		c.emitStatements(s.NotOnOverflow)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelEnd)
	}
}

func (c *Codegen) emitMove(s *parser.Move) {
	name := sanitize(s.To)
	switch from := s.From.(type) {
	case *parser.StringLiteralExpr:
		size := c.fieldSize(s.To)
		buf := make([]byte, size)
		copy(buf, from.Value)
		for i := len(from.Value); i < size; i++ {
			buf[i] = ' '
		}
		cn := c.addStringConst(buf)
		c.emit("call void @llvm.memcpy.p0.p0.i64("+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"i64 %d, i1 false)",
			size+1, name, size+1, cn, size+1)
	case *parser.IntegerLiteralExpr:
		c.emit("store i32 %d, ptr @%s", from.Value, name)
	case *parser.IdentifierExpr:
		fromName := sanitize(from.Name)
		c.emit("%%tmp = load i32, ptr @%s", fromName)
		c.emit("store i32 %%tmp, ptr @%s", name)
	}
}

func (c *Codegen) emitCompute(s *parser.Compute) {
	name := sanitize(s.Target)
	result := c.emitExpr(s.Expr)
	c.emit("store i32 %s, ptr @%s", result, name)
}

func (c *Codegen) emitExpr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IntegerLiteralExpr:
		tmp := c.nextRegister()
		c.emit("%%%s = add i32 %d, 0", tmp, e.Value)
		return "%" + tmp
	case *parser.IdentifierExpr:
		tmp := c.nextRegister()
		name := sanitize(e.Name)
		c.emit("%%%s = load i32, ptr @%s", tmp, name)
		return "%" + tmp
	case *parser.BinaryExpr:
		tmp := c.nextRegister()

		switch e.Operator {
		case parser.OpAdd, parser.OpSub, parser.OpMul, parser.OpDiv,
			parser.OpGt, parser.OpLt, parser.OpGe, parser.OpLe:
			left := c.emitExpr(e.Left)
			right := c.emitExpr(e.Right)
			switch e.Operator {
			case parser.OpAdd:
				c.emit("%%%s = add i32 %s, %s", tmp, left, right)
			case parser.OpSub:
				c.emit("%%%s = sub i32 %s, %s", tmp, left, right)
			case parser.OpMul:
				c.emit("%%%s = mul i32 %s, %s", tmp, left, right)
			case parser.OpDiv:
				c.emit("%%%s = sdiv i32 %s, %s", tmp, left, right)
			case parser.OpGt:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sgt i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpLt:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp slt i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpGe:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sge i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			case parser.OpLe:
				cmptmp := c.nextRegister()
				c.emit("%%%s = icmp sle i32 %s, %s", cmptmp, left, right)
				c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			}
			return "%" + tmp

		case parser.OpEq:
			// String comparison: use cob_picx_eq if either operand is a string
			_, leftIsStr := e.Left.(*parser.IdentifierExpr)
			_, rightIsStr := e.Right.(*parser.IdentifierExpr)
			_, leftIsLit := e.Left.(*parser.StringLiteralExpr)
			_, rightIsLit := e.Right.(*parser.StringLiteralExpr)

			if leftIsStr || rightIsStr || leftIsLit || rightIsLit {
				leftPtr := c.emitExprPtr(e.Left)
				rightPtr := c.emitExprPtr(e.Right)
				leftSize := c.exprSize(e.Left)
				c.emit("%%%s = call i32 @cob_picx_eq(ptr %s, i64 %d, ptr %s)",
					tmp, leftPtr, leftSize, rightPtr)
				return "%" + tmp
			}
			// Numeric comparison
			left := c.emitExpr(e.Left)
			right := c.emitExpr(e.Right)
			cmptmp := c.nextRegister()
			c.emit("%%%s = icmp eq i32 %s, %s", cmptmp, left, right)
			c.emit("%%%s = zext i1 %%%s to i32", tmp, cmptmp)
			return "%" + tmp
		}
		return "%" + tmp
	}
	return "0"
}

func (c *Codegen) emitPerform(s *parser.Perform) {
	if s.Varying != nil {
		c.emitPerformVarying(s)
		return
	}
	name := sanitize(s.Paragraph)
	c.emit("call void @%s()", name)
}

func (c *Codegen) emitPerformVarying(s *parser.Perform) {
	vp := s.Varying
	varName := sanitize(vp.Variable)

	// Initialize: var = from
	fromVal := c.emitExpr(vp.From)
	c.emit("store i32 %s, ptr @%s", fromVal, varName)

	labelCond := c.nextLabel("perf.cond")
	labelBody := c.nextLabel("perf.body")
	labelEnd := c.nextLabel("perf.end")

	c.emit("br label %%%s", labelCond)

	// Condition check
	c.emit("%s:", labelCond)
	c.indent++
	condVal := c.emitExpr(vp.Until)
	c.emit("%%perf_done = icmp ne i32 %s, 0", condVal)
	c.emit("br i1 %%perf_done, label %%%s, label %%%s", labelEnd, labelBody)
	c.indent--

	// Loop body
	c.emit("%s:", labelBody)
	c.indent++
	c.emitStatements(s.Body)
	// Increment: var = var + by
	varReg := c.nextRegister()
	byVal := c.emitExpr(vp.By)
	c.emit("%%%s = load i32, ptr @%s", varReg, varName)
	nextReg := c.nextRegister()
	c.emit("%%%s = add i32 %%%s, %s", nextReg, varReg, byVal)
	c.emit("store i32 %%%s, ptr @%s", nextReg, varName)
	c.emit("br label %%%s", labelCond)
	c.indent--

	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitIf(s *parser.If) {
	cond := c.emitExpr(s.Condition)
	labelThen := c.nextLabel("if.then")
	labelElse := c.nextLabel("if.else")
	labelMerge := c.nextLabel("if.end")

	c.emit("%%cmp = icmp ne i32 %s, 0", cond)
	c.emit("br i1 %%cmp, label %%%s, label %%%s", labelThen, labelElse)

	c.emit("%s:", labelThen)
	c.indent++
	c.emitStatements(s.ThenBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelElse)
	c.indent++
	c.emitStatements(s.ElseBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelMerge)
}

func (c *Codegen) emitEvaluate(s *parser.Evaluate) {
	subject := c.emitExpr(s.Subject)
	labelEnd := c.nextLabel("eval.end")

	for i, wc := range s.WhenClauses {
		labelNext := c.nextLabel("eval.next")
		labelBody := c.nextLabel("eval.body")

		whenVal := c.emitExpr(wc.Values[0])
		c.emit("%%cmp%d = icmp eq i32 %s, %s", i, subject, whenVal)
		c.emit("br i1 %%cmp%d, label %%%s, label %%%s", i, labelBody, labelNext)

		c.emit("%s:", labelBody)
		c.indent++
		c.emitStatements(wc.Body)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNext)
	}

	if len(s.WhenOther) > 0 {
		c.emitStatements(s.WhenOther)
	}

	c.emit("br label %%%s", labelEnd)
	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitExprPtr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		name := sanitize(e.Name)
		reg := c.nextRegister()
		sz := c.fieldSize(e.Name) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		return "%" + reg
	case *parser.StringLiteralExpr:
		cn := c.addStringConst([]byte(e.Value))
		sz := len(e.Value) + 1
		return fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", sz, cn)
	case *parser.IntegerLiteralExpr:
		s := fmt.Sprintf("%d", e.Value)
		cn := c.addStringConst([]byte(s))
		sz := len(s) + 1
		return fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", sz, cn)
	}
	return "null"
}

func (c *Codegen) emitHttpGet(s *parser.HttpGet) {
	c.emitHttpCall("cob_http_get", s.URL, nil, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpPost(s *parser.HttpPost) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_post", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPut(s *parser.HttpPut) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_put", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPatch(s *parser.HttpPatch) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_patch", s.URL, sending, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpDelete(s *parser.HttpDelete) {
	c.emitHttpCall("cob_http_delete", s.URL, nil, s.Giving, s.Mapping, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpCall(funcName string, urlExpr parser.Expression, sendingExpr parser.Expression,
	giving, mapping *string, status string, onException, notOnException []parser.Statement, hasBody bool) {

	urlPtr := c.emitExprPtr(urlExpr)

	bodyPtr := "null"
	if hasBody && sendingExpr != nil {
		bodyPtr = c.emitExprPtr(sendingExpr)
	}

	// Response buffer: either the GIVING field or a temp alloca for MAPPING
	respPtr := "null"
	respSize := int64(0)
	lenReg := c.nextRegister()
	c.emit("%%%s = alloca i64, i64 1", lenReg)
	c.emit("store i64 0, ptr %%%s", lenReg)

	if giving != nil {
		name := sanitize(*giving)
		reg := c.nextRegister()
		sz := c.fieldSize(*giving) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		respPtr = "%" + reg
		respSize = int64(sz)
	} else if mapping != nil {
		// Allocate temp buffer for JSON response, 4096 bytes
		bufReg := c.nextRegister()
		c.emit("%%%s = alloca [4096 x i8], i64 1", bufReg)
		respReg := c.nextRegister()
		c.emit("%%%s = getelementptr [4096 x i8], ptr %%%s, i64 0, i64 0",
			respReg, bufReg)
		respPtr = "%" + respReg
		respSize = 4096
	}

	statusPtr := "null"
	if status != "" {
		statusPtr = "@" + sanitize(status)
	}

	resultReg := c.nextRegister()
	if hasBody {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, bodyPtr, respPtr, respSize, lenReg, statusPtr)
	} else {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, respPtr, respSize, lenReg, statusPtr)
	}

	// If MAPPING, emit per-field JSON extraction
	if mapping != nil {
		c.emitJsonMapping(*mapping, respPtr, lenReg)
	}

	hasOn := len(onException) > 0
	hasNotOn := len(notOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(onException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(notOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

func (c *Codegen) emitJsonMapping(groupName, respPtr, lenReg string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	lenV := c.nextRegister()
	c.emit("%%%s = load i64, ptr %%%s", lenV, lenReg)

	for _, child := range children {
		if child.Picture == nil {
			continue
		}
		fn := c.addStringConst([]byte(child.Name))
		fnSz := len(child.Name) + 1
		fnGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", fnSz, fn)

		switch child.Picture.Type {
		case parser.PicX:
			fieldReg := c.nextRegister()
			sz := child.Picture.Size + 1
			c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
				fieldReg, sz, sanitize(child.Name))
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_json_str(ptr %s, i64 %%%s, ptr %s, ptr %%%s, i64 %d)",
				discard, respPtr, lenV, fnGep, fieldReg, int64(child.Picture.Size))
		case parser.Pic9:
			fieldPtr := "@" + sanitize(child.Name)
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_json_int(ptr %s, i64 %%%s, ptr %s, ptr %s)",
				discard, respPtr, lenV, fnGep, fieldPtr)
		}
	}
}

func (c *Codegen) emitHttpListen(s *parser.HttpListen) {
	resultReg := c.nextRegister()
	statusPtr := "null"
	if s.Status != "" {
		statusPtr = "@" + sanitize(s.Status)
	}
	c.emit("%%%s = call i32 @cob_http_listen(i32 %d, ptr %s)",
		resultReg, s.Port, statusPtr)

	if s.Mapping != nil {
		c.emitHttpListenMapping(*s.Mapping)
	}
	if s.Headers != nil && s.Headers.Group != "" {
		c.emitHttpListenMapping(s.Headers.Group)
	}

	hasOn := len(s.OnException) > 0
	hasNotOn := len(s.NotOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(s.OnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(s.NotOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

func (c *Codegen) emitHttpListenMapping(groupName string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	for _, child := range children {
		if child.Picture == nil {
			continue
		}
		fn := c.addStringConst([]byte(child.Name))
		fnSz := len(child.Name) + 1
		fnGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", fnSz, fn)

		switch child.Picture.Type {
		case parser.PicX:
			fieldReg := c.nextRegister()
			sz := child.Picture.Size + 1
			c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
				fieldReg, sz, sanitize(child.Name))
			discard := c.nextRegister()
			c.emit("%%%s = call i32 @cob_http_request_field(ptr %s, ptr %%%s, i64 %d)",
				discard, fnGep, fieldReg, int64(child.Picture.Size))
		}
	}
}

func (c *Codegen) emitHttpRespondHeaders(groupName string) {
	children := c.findGroupChildren(groupName)
	if children == nil {
		return
	}
	for _, child := range children {
		if child.Picture == nil || child.Picture.Type != parser.PicX {
			continue
		}
		hdrName := c.addStringConst([]byte(child.Name))
		hdrNameSz := len(child.Name) + 1
		hdrNameGep := fmt.Sprintf("getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0)", hdrNameSz, hdrName)

		fieldReg := c.nextRegister()
		sz := child.Picture.Size + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			fieldReg, sz, sanitize(child.Name))
		discard := c.nextRegister()
		c.emit("%%%s = call i32 @cob_http_respond_set_header(ptr %s, ptr %%%s, i64 %d)",
			discard, hdrNameGep, fieldReg, int64(child.Picture.Size))
	}
}

func (c *Codegen) emitHttpRespond(s *parser.HttpRespond) {
	if s.Headers != nil && s.Headers.Group != "" {
		c.emitHttpRespondHeaders(s.Headers.Group)
	}

	bodyPtr := "null"
	if s.Body != nil {
		bodyPtr = c.emitExprPtr(s.Body)
	}
	contentTypePtr := "null"
	if s.ContentType != nil {
		contentTypePtr = c.emitExprPtr(s.ContentType)
	}

	resultReg := c.nextRegister()
	c.emit("%%%s = call i32 @cob_http_respond(i32 %d, ptr %s, ptr %s)",
		resultReg, s.Status, bodyPtr, contentTypePtr)

	hasOn := len(s.OnException) > 0
	hasNotOn := len(s.NotOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(s.OnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(s.NotOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

var registerCounter int
var labelCounter int

func (c *Codegen) nextRegister() string {
	registerCounter++
	return fmt.Sprintf("r%d", registerCounter)
}

func (c *Codegen) nextLabel(prefix string) string {
	labelCounter++
	return fmt.Sprintf("%s.%d", prefix, labelCounter)
}

func sanitize(name string) string {
	s := strings.ReplaceAll(name, "-", "_")
	s = strings.ReplaceAll(s, "<", "_")
	s = strings.ReplaceAll(s, ">", "_")
	return "cob." + s
}

func (c *Codegen) firstParagraphName() string {
	if c.prog.ProcedureDivision != nil && len(c.prog.ProcedureDivision.Paragraphs) > 0 {
		return sanitize(c.prog.ProcedureDivision.Paragraphs[0].Name)
	}
	return ""
}

func (c *Codegen) fieldSize(name string) int {
	if c.prog.WorkingStorage == nil {
		return 0
	}
	return findFieldSize(name, c.prog.WorkingStorage.Items)
}

func (c *Codegen) exprSize(expr parser.Expression) int64 {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return int64(c.fieldSize(e.Name))
	case *parser.StringLiteralExpr:
		return int64(len(e.Value))
	case *parser.IntegerLiteralExpr:
		return 4
	}
	return 1
}

func (c *Codegen) exprName(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return e.Name
	case *parser.StringLiteralExpr:
		return ""
	case *parser.IntegerLiteralExpr:
		return ""
	}
	return ""
}

func (c *Codegen) exprValueSize(expr parser.Expression) int64 {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		return int64(c.fieldSize(e.Name))
	case *parser.StringLiteralExpr:
		return int64(len(e.Value))
	case *parser.IntegerLiteralExpr:
		return 4 // max int32 digits (no null terminator needed)
	}
	return 1
}

func (c *Codegen) isNumericField(name string) bool {
	if c.prog.WorkingStorage == nil {
		return false
	}
	return findFieldType(name, c.prog.WorkingStorage.Items)
}

func findFieldType(name string, items []*parser.DataItem) bool {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Type == parser.Pic9
		}
		if len(item.Children) > 0 {
			if num := findFieldType(name, item.Children); num {
				return true
			}
		}
	}
	return false
}

func findFieldSize(name string, items []*parser.DataItem) int {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Size
		}
		if len(item.Children) > 0 {
			if size := findFieldSize(name, item.Children); size > 0 {
				return size
			}
		}
	}
	return 0
}

func (c *Codegen) findGroupChildren(name string) []*parser.DataItem {
	if c.prog.WorkingStorage == nil {
		return nil
	}
	return findGroupItemChildren(name, c.prog.WorkingStorage.Items)
}

func findGroupItemChildren(name string, items []*parser.DataItem) []*parser.DataItem {
	for _, item := range items {
		if item.Name == name {
			return item.Children
		}
		if len(item.Children) > 0 {
			if found := findGroupItemChildren(name, item.Children); found != nil {
				return found
			}
		}
	}
	return nil
}
