package codegen

import (
	"fmt"
	"strings"

	"github.com/KDreynolds/COBOLabunga/parser"
)

type stringConst struct {
	name string
	data []byte
}

type Codegen struct {
	prog      *parser.Program
	buf       strings.Builder
	indent    int
	strConsts []stringConst
}

func New(prog *parser.Program) *Codegen {
	return &Codegen{prog: prog}
}

func (c *Codegen) Generate() string {
	c.buf.Reset()
	c.strConsts = nil

	c.emit("; Generated by COBOLabunga v0.1")
	c.emit("target triple = \"x86_64-pc-linux-gnu\"")
	c.emit("")

	c.emit("declare i32 @puts(ptr)")
	c.emit("declare i32 @printf(ptr, ...)")
	c.emit("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)")
	c.emit("")
	c.emit("declare i32 @cob_http_get(ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_post(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_put(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_patch(ptr, ptr, ptr, i64, ptr, ptr)")
	c.emit("declare i32 @cob_http_delete(ptr, ptr, i64, ptr, ptr)")
	c.emit("")

	c.emitWorkingStorage()
	c.emitMain()

	if c.prog.ProcedureDivision != nil {
		for _, para := range c.prog.ProcedureDivision.Paragraphs {
			c.emitParagraph(para)
		}
	}

	c.emitStringConsts()
	return c.buf.String()
}

func (c *Codegen) emit(format string, args ...interface{}) {
	for i := 0; i < c.indent; i++ {
		c.buf.WriteString("  ")
	}
	c.buf.WriteString(fmt.Sprintf(format, args...))
	c.buf.WriteString("\n")
}

func (c *Codegen) emitWorkingStorage() {
	if c.prog.WorkingStorage == nil {
		return
	}
	for _, item := range c.prog.WorkingStorage.Items {
		c.emitDataItem(item)
	}
	if len(c.prog.WorkingStorage.Items) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitDataItem(item *parser.DataItem) {
	if len(item.Children) > 0 || item.Picture == nil {
		return
	}
	name := sanitize(item.Name)
	switch item.Picture.Type {
	case parser.PicX:
		size := item.Picture.Size
		init := c.picXInitializer(item.Value, size)
		c.emit("@%s = global [%d x i8] %s", name, size+1, init)
	case parser.Pic9:
		init := c.pic9Initializer(item.Value)
		c.emit("@%s = global i32 %s", name, init)
	}
}

func (c *Codegen) picXInitializer(value string, size int) string {
	buf := make([]byte, size)
	copy(buf, value)
	for i := len(value); i < size; i++ {
		buf[i] = ' '
	}
	return c.llvmArrayInit(buf)
}

func (c *Codegen) pic9Initializer(value string) string {
	if value == "" {
		return "0"
	}
	return value
}

func (c *Codegen) llvmArrayInit(data []byte) string {
	var sb strings.Builder
	sb.WriteString("[")
	for i, b := range data {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("i8 %d", uint8(b)))
	}
	sb.WriteString(", i8 0]")
	return sb.String()
}

func (c *Codegen) addStringConst(data []byte) string {
	name := fmt.Sprintf(".str.%d", len(c.strConsts))
	c.strConsts = append(c.strConsts, stringConst{name: name, data: data})
	return name
}

func (c *Codegen) emitStringConsts() {
	for _, sc := range c.strConsts {
		init := c.llvmArrayInit(sc.data)
		c.emit("@%s = private unnamed_addr constant [%d x i8] %s",
			sc.name, len(sc.data)+1, init)
	}
	if len(c.strConsts) > 0 {
		c.emit("")
	}
}

func (c *Codegen) emitMain() {
	c.emit("define i32 @main() {")
	c.indent++
	firstPara := c.firstParagraphName()
	if firstPara != "" {
		c.emit("call void @%s()", firstPara)
	}
	c.emit("ret i32 0")
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitParagraph(para *parser.Paragraph) {
	name := sanitize(para.Name)
	c.emit("define void @%s() {", name)
	c.indent++
	c.emit("entry:")
	c.indent++
	c.emitStatements(para.Statements)
	c.indent--
	c.indent--
	c.emit("}")
	c.emit("")
}

func (c *Codegen) emitStatements(stmts []parser.Statement) {
	for _, stmt := range stmts {
		c.emitStatement(stmt)
	}
}

func (c *Codegen) emitStatement(stmt parser.Statement) {
	switch s := stmt.(type) {
	case *parser.Display:
		c.emitDisplay(s)
	case *parser.StopRun:
		c.emit("ret void")
	case *parser.Move:
		c.emitMove(s)
	case *parser.Compute:
		c.emitCompute(s)
	case *parser.Perform:
		c.emitPerform(s)
	case *parser.If:
		c.emitIf(s)
	case *parser.Evaluate:
		c.emitEvaluate(s)
	case *parser.HttpGet:
		c.emitHttpGet(s)
	case *parser.HttpPost:
		c.emitHttpPost(s)
	case *parser.HttpPut:
		c.emitHttpPut(s)
	case *parser.HttpPatch:
		c.emitHttpPatch(s)
	case *parser.HttpDelete:
		c.emitHttpDelete(s)
	}
}

func (c *Codegen) emitDisplay(s *parser.Display) {
	for _, item := range s.Items {
		switch expr := item.(type) {
		case *parser.IdentifierExpr:
			if c.isNumericField(expr.Name) {
				reg := c.nextRegister()
				cn := c.addStringConst([]byte("%d"))
				c.emit("%%%s = load i32, ptr @%s", reg, sanitize(expr.Name))
				c.emit("call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @%s, i64 0, i64 0), i32 %%%s)",
					cn, reg)
			} else {
				name := sanitize(expr.Name)
				reg := c.nextRegister()
				c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
					reg, c.fieldSize(expr.Name)+1, name)
				c.emit("call i32 @puts(ptr %%%s)", reg)
			}
		case *parser.StringLiteralExpr:
			cn := c.addStringConst([]byte(expr.Value))
			sz := len(expr.Value) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		case *parser.IntegerLiteralExpr:
			str := fmt.Sprintf("%d", expr.Value)
			cn := c.addStringConst([]byte(str))
			sz := len(str) + 1
			c.emit("call i32 @puts(ptr getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0))",
				sz, cn)
		}
	}
}

func (c *Codegen) emitMove(s *parser.Move) {
	name := sanitize(s.To)
	switch from := s.From.(type) {
	case *parser.StringLiteralExpr:
		size := c.fieldSize(s.To)
		buf := make([]byte, size)
		copy(buf, from.Value)
		for i := len(from.Value); i < size; i++ {
			buf[i] = ' '
		}
		cn := c.addStringConst(buf)
		c.emit("call void @llvm.memcpy.p0.p0.i64("+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"ptr align 1 getelementptr inbounds ([%d x i8], ptr @%s, i64 0, i64 0), "+
			"i64 %d, i1 false)",
			size+1, name, size+1, cn, size+1)
	case *parser.IntegerLiteralExpr:
		c.emit("store i32 %d, ptr @%s", from.Value, name)
	case *parser.IdentifierExpr:
		fromName := sanitize(from.Name)
		c.emit("%%tmp = load i32, ptr @%s", fromName)
		c.emit("store i32 %%tmp, ptr @%s", name)
	}
}

func (c *Codegen) emitCompute(s *parser.Compute) {
	name := sanitize(s.Target)
	result := c.emitExpr(s.Expr)
	c.emit("store i32 %s, ptr @%s", result, name)
}

func (c *Codegen) emitExpr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IntegerLiteralExpr:
		tmp := c.nextRegister()
		c.emit("%%%s = add i32 %d, 0", tmp, e.Value)
		return "%" + tmp
	case *parser.IdentifierExpr:
		tmp := c.nextRegister()
		name := sanitize(e.Name)
		c.emit("%%%s = load i32, ptr @%s", tmp, name)
		return "%" + tmp
	case *parser.BinaryExpr:
		left := c.emitExpr(e.Left)
		right := c.emitExpr(e.Right)
		tmp := c.nextRegister()
		op := ""
		switch e.Operator {
		case parser.OpAdd:
			op = "add"
		case parser.OpSub:
			op = "sub"
		case parser.OpMul:
			op = "mul"
		case parser.OpDiv:
			op = "sdiv"
		}
		c.emit("%%%s = %s i32 %s, %s", tmp, op, left, right)
		return "%" + tmp
	}
	return "0"
}

func (c *Codegen) emitPerform(s *parser.Perform) {
	name := sanitize(s.Paragraph)
	c.emit("call void @%s()", name)
}

func (c *Codegen) emitIf(s *parser.If) {
	cond := c.emitExpr(s.Condition)
	labelThen := c.nextLabel("if.then")
	labelElse := c.nextLabel("if.else")
	labelMerge := c.nextLabel("if.end")

	c.emit("%%cmp = icmp ne i32 %s, 0", cond)
	c.emit("br i1 %%cmp, label %%%s, label %%%s", labelThen, labelElse)

	c.emit("%s:", labelThen)
	c.indent++
	c.emitStatements(s.ThenBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelElse)
	c.indent++
	c.emitStatements(s.ElseBody)
	c.emit("br label %%%s", labelMerge)
	c.indent--

	c.emit("%s:", labelMerge)
}

func (c *Codegen) emitEvaluate(s *parser.Evaluate) {
	subject := c.emitExpr(s.Subject)
	labelEnd := c.nextLabel("eval.end")

	for i, wc := range s.WhenClauses {
		labelNext := c.nextLabel("eval.next")
		labelBody := c.nextLabel("eval.body")

		whenVal := c.emitExpr(wc.Values[0])
		c.emit("%%cmp%d = icmp eq i32 %s, %s", i, subject, whenVal)
		c.emit("br i1 %%cmp%d, label %%%s, label %%%s", i, labelBody, labelNext)

		c.emit("%s:", labelBody)
		c.indent++
		c.emitStatements(wc.Body)
		c.emit("br label %%%s", labelEnd)
		c.indent--

		c.emit("%s:", labelNext)
	}

	if len(s.WhenOther) > 0 {
		c.emitStatements(s.WhenOther)
	}

	c.emit("br label %%%s", labelEnd)
	c.emit("%s:", labelEnd)
}

func (c *Codegen) emitExprPtr(expr parser.Expression) string {
	switch e := expr.(type) {
	case *parser.IdentifierExpr:
		name := sanitize(e.Name)
		reg := c.nextRegister()
		sz := c.fieldSize(e.Name) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		return "%" + reg
	case *parser.StringLiteralExpr:
		cn := c.addStringConst([]byte(e.Value))
		reg := c.nextRegister()
		sz := len(e.Value) + 1
		c.emit("%%%s = getelementptr inbounds [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, cn)
		return "%" + reg
	case *parser.IntegerLiteralExpr:
		cn := c.addStringConst([]byte(fmt.Sprintf("%d", e.Value)))
		reg := c.nextRegister()
		sz := len(fmt.Sprintf("%d", e.Value)) + 1
		c.emit("%%%s = getelementptr inbounds [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, cn)
		return "%" + reg
	}
	return "null"
}

func (c *Codegen) emitHttpGet(s *parser.HttpGet) {
	c.emitHttpCall("cob_http_get", s.URL, nil, s.Giving, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpPost(s *parser.HttpPost) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_post", s.URL, sending, s.Giving, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPut(s *parser.HttpPut) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_put", s.URL, sending, s.Giving, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpPatch(s *parser.HttpPatch) {
	sending := parser.Expression(s.Sending)
	c.emitHttpCall("cob_http_patch", s.URL, sending, s.Giving, s.Status, s.OnException, s.NotOnException, true)
}

func (c *Codegen) emitHttpDelete(s *parser.HttpDelete) {
	c.emitHttpCall("cob_http_delete", s.URL, nil, s.Giving, s.Status, s.OnException, s.NotOnException, false)
}

func (c *Codegen) emitHttpCall(funcName string, urlExpr parser.Expression, sendingExpr parser.Expression,
	giving *string, status string, onException, notOnException []parser.Statement, hasBody bool) {

	urlPtr := c.emitExprPtr(urlExpr)

	bodyPtr := "null"
	if hasBody && sendingExpr != nil {
		bodyPtr = c.emitExprPtr(sendingExpr)
	}

	respPtr := "null"
	respSize := int64(0)
	if giving != nil {
		name := sanitize(*giving)
		reg := c.nextRegister()
		sz := c.fieldSize(*giving) + 1
		c.emit("%%%s = getelementptr [%d x i8], ptr @%s, i64 0, i64 0",
			reg, sz, name)
		respPtr = "%" + reg
		respSize = int64(sz)
	}

	lenReg := c.nextRegister()
	c.emit("%%%s = alloca i64, i64 1", lenReg)
	c.emit("store i64 0, ptr %%%s", lenReg)

	statusPtr := "null"
	if status != "" {
		statusPtr = "@" + sanitize(status)
	}

	resultReg := c.nextRegister()
	if hasBody {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, bodyPtr, respPtr, respSize, lenReg, statusPtr)
	} else {
		c.emit("%%%s = call i32 @%s(ptr %s, ptr %s, i64 %d, ptr %%%s, ptr %s)",
			resultReg, funcName, urlPtr, respPtr, respSize, lenReg, statusPtr)
	}

	hasOn := len(onException) > 0
	hasNotOn := len(notOnException) > 0

	if hasOn || hasNotOn {
		labelOk := c.nextLabel("http.ok")
		labelErr := c.nextLabel("http.err")
		labelMerge := c.nextLabel("http.end")

		c.emit("%%is_ok = icmp eq i32 %%%s, 0", resultReg)
		c.emit("br i1 %%is_ok, label %%%s, label %%%s", labelOk, labelErr)

		c.emit("%s:", labelErr)
		c.indent++
		if hasOn {
			c.emitStatements(onException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelOk)
		c.indent++
		if hasNotOn {
			c.emitStatements(notOnException)
		}
		c.emit("br label %%%s", labelMerge)
		c.indent--

		c.emit("%s:", labelMerge)
	}
}

var registerCounter int
var labelCounter int

func (c *Codegen) nextRegister() string {
	registerCounter++
	return fmt.Sprintf("r%d", registerCounter)
}

func (c *Codegen) nextLabel(prefix string) string {
	labelCounter++
	return fmt.Sprintf("%s.%d", prefix, labelCounter)
}

func sanitize(name string) string {
	s := strings.ReplaceAll(name, "-", "_")
	return "cob." + s
}

func (c *Codegen) firstParagraphName() string {
	if c.prog.ProcedureDivision != nil && len(c.prog.ProcedureDivision.Paragraphs) > 0 {
		return sanitize(c.prog.ProcedureDivision.Paragraphs[0].Name)
	}
	return ""
}

func (c *Codegen) fieldSize(name string) int {
	if c.prog.WorkingStorage == nil {
		return 0
	}
	return findFieldSize(name, c.prog.WorkingStorage.Items)
}

func (c *Codegen) isNumericField(name string) bool {
	if c.prog.WorkingStorage == nil {
		return false
	}
	return findFieldType(name, c.prog.WorkingStorage.Items)
}

func findFieldType(name string, items []*parser.DataItem) bool {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Type == parser.Pic9
		}
		if len(item.Children) > 0 {
			if num := findFieldType(name, item.Children); num {
				return true
			}
		}
	}
	return false
}

func findFieldSize(name string, items []*parser.DataItem) int {
	for _, item := range items {
		if item.Name == name && item.Picture != nil {
			return item.Picture.Size
		}
		if len(item.Children) > 0 {
			if size := findFieldSize(name, item.Children); size > 0 {
				return size
			}
		}
	}
	return 0
}
